/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 31 21:24:09 GMT 2017
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PipedWriter;
import java.io.Writer;
import java.nio.charset.Charset;
import org.apache.commons.lang3.text.translate.AggregateTranslator;
import org.apache.commons.lang3.text.translate.CharSequenceTranslator;
import org.apache.commons.lang3.text.translate.NumericEntityEscaper;
import org.apache.commons.lang3.text.translate.UnicodeEscaper;
import org.apache.commons.lang3.text.translate.UnicodeUnescaper;
import org.apache.commons.lang3.text.translate.UnicodeUnpairedSurrogateRemover;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;
import sun.nio.cs.US_ASCII;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.lang.reflect.Field;
import org.apache.commons.lang3.reflect.FieldUtils;
import static org.junit.Assert.*;
import myprinter.FieldPrinter;

public class DiffTGen0Test {

  //Test case number: 0
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;: Line 126
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;
   * Goal 4. Weak Mutation 107: org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;:126 - InsertUnaryOp Negation of codepoint
   * Goal 5. Weak Mutation 108: org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;:126 - InsertUnaryOp IINC 1 codepoint
   * Goal 6. Weak Mutation 109: org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;:126 - InsertUnaryOp IINC -1 codepoint
   */

  

  //Test case number: 1
  /*
   * 19 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;: Line 112
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;: Line 113
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;: Line 114
   * Goal 4. org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;: Line 115
   * Goal 5. org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;
   * Goal 6. org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;
   * Goal 7. Weak Mutation 94: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:112 - ReplaceConstant - 1 -> 0
   * Goal 8. Weak Mutation 95: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:112 - ReplaceArithmeticOperator + -> %
   * Goal 9. Weak Mutation 96: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:112 - ReplaceArithmeticOperator + -> -
   * Goal 10. Weak Mutation 97: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:112 - ReplaceArithmeticOperator + -> *
   * Goal 11. Weak Mutation 98: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:112 - ReplaceArithmeticOperator + -> /
   * Goal 12. Weak Mutation 99: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:113 - ReplaceVariable newArray -> translators
   * Goal 13. Weak Mutation 100: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:113 - ReplaceConstant - 0 -> 1
   * Goal 14. Weak Mutation 101: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:114 - ReplaceVariable translators -> newArray
   * Goal 15. Weak Mutation 102: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:114 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 103: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:114 - ReplaceVariable newArray -> translators
   * Goal 17. Weak Mutation 104: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:114 - ReplaceConstant - 1 -> 0
   * Goal 18. Weak Mutation 105: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:114 - ReplaceVariable translators -> newArray
   * Goal 19. Weak Mutation 106: org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;:115 - ReplaceVariable newArray -> translators
   */

  

  //Test case number: 2
  /*
   * 15 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 76
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 78
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 80
   * Goal 4. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 83
   * Goal 5. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 84
   * Goal 6. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V
   * Goal 7. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V
   * Goal 8. Weak Mutation 10: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator = null -> != null
   * Goal 9. Weak Mutation 12: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator != null -> = null
   * Goal 10. Weak Mutation 13: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator != null -> = null
   * Goal 11. Weak Mutation 14: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> 0
   * Goal 12. Weak Mutation 15: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> 1
   * Goal 13. Weak Mutation 16: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> -2
   * Goal 14. Weak Mutation 17: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:80 - ReplaceComparisonOperator = null -> != null
   * Goal 15. Weak Mutation 20: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:83 - ReplaceComparisonOperator != null -> = null
   */

  

  //Test case number: 3
  /*
   * 5 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;: Line 54
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;: Line 55
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;
   * Goal 4. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;
   * Goal 5. Weak Mutation 0: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:54 - ReplaceComparisonOperator != null -> = null
   */

  

  //Test case number: 4
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;: Line 126
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 4. Weak Mutation 107: org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;:126 - InsertUnaryOp Negation of codepoint
   * Goal 5. Weak Mutation 108: org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;:126 - InsertUnaryOp IINC 1 codepoint
   * Goal 6. Weak Mutation 109: org.apache.commons.lang3.text.translate.CharSequenceTranslator.hex(I)Ljava/lang/String;:126 - InsertUnaryOp IINC -1 codepoint
   */

  

  //Test case number: 5
  /*
   * 3 covered goals:
   * Goal 1. with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;: Line 112
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.with([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;
   */

  

  //Test case number: 6
  /*
   * 44 covered goals:
   * Goal 1. translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 76
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 78
   * Goal 4. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 80
   * Goal 5. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 83
   * Goal 6. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 86
   * Goal 7. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 87
   * Goal 8. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 88
   * Goal 9. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 89
   * Goal 10. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 90
   * Goal 11. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 91
   * Goal 12. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 92
   * Goal 13. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V
   * Goal 14. Weak Mutation 10: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator = null -> != null
   * Goal 15. Weak Mutation 12: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator != null -> = null
   * Goal 16. Weak Mutation 13: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator != null -> = null
   * Goal 17. Weak Mutation 14: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> 0
   * Goal 18. Weak Mutation 15: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> 1
   * Goal 19. Weak Mutation 16: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> -2
   * Goal 20. Weak Mutation 17: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:80 - ReplaceComparisonOperator = null -> != null
   * Goal 21. Weak Mutation 20: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:83 - ReplaceComparisonOperator != null -> = null
   * Goal 22. Weak Mutation 21: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:86 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 22: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - ReplaceVariable pos -> len
   * Goal 24. Weak Mutation 23: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - InsertUnaryOp Negation of pos
   * Goal 25. Weak Mutation 24: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - InsertUnaryOp IINC 1 pos
   * Goal 26. Weak Mutation 25: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - InsertUnaryOp IINC -1 pos
   * Goal 27. Weak Mutation 26: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - ReplaceVariable len -> pos
   * Goal 28. Weak Mutation 27: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - InsertUnaryOp Negation of len
   * Goal 29. Weak Mutation 28: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - InsertUnaryOp IINC 1 len
   * Goal 30. Weak Mutation 29: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - InsertUnaryOp IINC -1 len
   * Goal 31. Weak Mutation 30: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:88 - ReplaceComparisonOperator >= -> -1
   * Goal 32. Weak Mutation 33: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:89 - ReplaceVariable pos -> len
   * Goal 33. Weak Mutation 34: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:89 - InsertUnaryOp Negation of pos
   * Goal 34. Weak Mutation 35: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:89 - InsertUnaryOp IINC 1 pos
   * Goal 35. Weak Mutation 36: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:89 - InsertUnaryOp IINC -1 pos
   * Goal 36. Weak Mutation 37: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:90 - ReplaceVariable consumed -> len
   * Goal 37. Weak Mutation 39: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:90 - InsertUnaryOp Negation of consumed
   * Goal 38. Weak Mutation 40: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:90 - InsertUnaryOp IINC 1 consumed
   * Goal 39. Weak Mutation 41: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:90 - InsertUnaryOp IINC -1 consumed
   * Goal 40. Weak Mutation 42: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:90 - ReplaceComparisonOperator != -> -1
   * Goal 41. Weak Mutation 46: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:91 - ReplaceVariable pos -> len
   * Goal 42. Weak Mutation 47: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:91 - InsertUnaryOp Negation of pos
   * Goal 43. Weak Mutation 48: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:91 - InsertUnaryOp IINC 1 pos
   * Goal 44. Weak Mutation 49: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:91 - InsertUnaryOp IINC -1 pos
   */

  @Test public void test6()  throws Throwable  {
	Object target_obj_7au3e = null;
	boolean not_thrown = false;
	try {
		CharSequenceTranslator.clearORefMap();
		UnicodeUnpairedSurrogateRemover unicodeUnpairedSurrogateRemover0 = new UnicodeUnpairedSurrogateRemover();
		try {
			unicodeUnpairedSurrogateRemover0.translate((CharSequence) "8",
					(Writer) null);
		} catch (NullPointerException e) {
			assertThrownBy(
					"org.apache.commons.lang3.text.translate.CharSequenceTranslator",
					e);
		}
		not_thrown = true;
		fail();
	} catch (Throwable t) {
		if (not_thrown) {
			fail("Throwable Expected!");
		} else {
			List obj_list_7au3e = (List) CharSequenceTranslator.oref_map
					.get("translate(CharSequence$Writer)0");
			target_obj_7au3e = obj_list_7au3e.get(0);
			assertEquals(
					"(E)0,(C)org.apache.commons.lang3.text.translate.CharSequenceTranslator,(MSIG)translate(CharSequence$Writer)0,(I)0",
					"java.lang.IllegalArgumentException: The Writer must not be null",
					((Throwable) target_obj_7au3e).toString());
		}
	}
}

  //Test case number: 7
  /*
   * 14 covered goals:
   * Goal 1. translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 76
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 78
   * Goal 4. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 80
   * Goal 5. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 81
   * Goal 6. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V
   * Goal 7. Weak Mutation 10: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator = null -> != null
   * Goal 8. Weak Mutation 11: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator != null -> = null
   * Goal 9. Weak Mutation 14: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> 0
   * Goal 10. Weak Mutation 15: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> 1
   * Goal 11. Weak Mutation 16: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> -2
   * Goal 12. Weak Mutation 17: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:80 - ReplaceComparisonOperator = null -> != null
   * Goal 13. Weak Mutation 18: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:81 - ReplaceConstant - The Writer must not be null -> 
   * Goal 14. Weak Mutation 19: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:81 - ReplaceComparisonOperator == -> !=
   */

  //Test case number: 8
  /*
   * 26 covered goals:
   * Goal 1. translate(Ljava/lang/CharSequence;)Ljava/lang/String;_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 2. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;: Line 54
   * Goal 3. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;: Line 58
   * Goal 4. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;: Line 59
   * Goal 5. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 76
   * Goal 6. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 78
   * Goal 7. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 80
   * Goal 8. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V: Line 81
   * Goal 9. org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;
   * Goal 10. Weak Mutation 0: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:54 - ReplaceComparisonOperator != null -> = null
   * Goal 11. Weak Mutation 1: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:58 - ReplaceConstant - 2 -> 0
   * Goal 12. Weak Mutation 2: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:58 - ReplaceConstant - 2 -> 1
   * Goal 13. Weak Mutation 3: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:58 - ReplaceConstant - 2 -> -1
   * Goal 14. Weak Mutation 4: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:58 - ReplaceConstant - 2 -> 3
   * Goal 15. Weak Mutation 5: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:58 - ReplaceArithmeticOperator * -> +
   * Goal 16. Weak Mutation 6: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:58 - ReplaceArithmeticOperator * -> %
   * Goal 17. Weak Mutation 7: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:58 - ReplaceArithmeticOperator * -> -
   * Goal 18. Weak Mutation 8: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;)Ljava/lang/String;:58 - ReplaceArithmeticOperator * -> /
   * Goal 19. Weak Mutation 10: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator = null -> != null
   * Goal 20. Weak Mutation 11: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:76 - ReplaceComparisonOperator != null -> = null
   * Goal 21. Weak Mutation 14: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> 0
   * Goal 22. Weak Mutation 15: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> 1
   * Goal 23. Weak Mutation 16: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:78 - ReplaceConstant - -1 -> -2
   * Goal 24. Weak Mutation 17: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:80 - ReplaceComparisonOperator = null -> != null
   * Goal 25. Weak Mutation 18: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:81 - ReplaceConstant - The Writer must not be null -> 
   * Goal 26. Weak Mutation 19: org.apache.commons.lang3.text.translate.CharSequenceTranslator.translate(Ljava/lang/CharSequence;Ljava/io/Writer;)V:81 - ReplaceComparisonOperator == -> !=
   */
}
