/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 31 22:25:12 GMT 2017
 */

package org.apache.commons.math3.distribution;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.apache.commons.math3.distribution.DiscreteDistribution;
import org.apache.commons.math3.random.ISAACRandom;
import org.apache.commons.math3.random.MersenneTwister;
import org.apache.commons.math3.random.RandomAdaptorTest;
import org.apache.commons.math3.random.RandomGenerator;
import org.apache.commons.math3.random.SynchronizedRandomGenerator;
import org.apache.commons.math3.random.Well19937c;
import org.apache.commons.math3.random.Well44497b;
import org.apache.commons.math3.util.Pair;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.lang.reflect.Field;
import org.apache.commons.lang3.reflect.FieldUtils;
import static org.junit.Assert.*;
import myprinter.FieldPrinter;

public class DiffTGen0Test {

  //Test case number: 0
  /*
   * 64 covered goals:
   * Goal 1. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 102
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 157
   * Goal 12. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 158
   * Goal 13. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 160
   * Goal 14. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 161
   * Goal 15. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 162
   * Goal 16. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 163
   * Goal 17. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 18. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;
   * Goal 19. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 20. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;
   * Goal 21. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 22. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 24. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 25. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 26. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 27. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 28. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 29. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 30. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 31. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 32. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 33. Weak Mutation 14: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> ==
   * Goal 34. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 35. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 36. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 37. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 38. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 39. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   * Goal 40. Weak Mutation 64: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:158 - ReplaceConstant - 0.0 -> 1.0
   * Goal 41. Weak Mutation 65: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:158 - ReplaceConstant - 0.0 -> -1.0
   * Goal 42. Weak Mutation 66: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - ReplaceConstant - 0 -> 1
   * Goal 43. Weak Mutation 67: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - InsertUnaryOp Negation of i
   * Goal 44. Weak Mutation 68: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - InsertUnaryOp IINC 1 i
   * Goal 45. Weak Mutation 69: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - InsertUnaryOp IINC -1 i
   * Goal 46. Weak Mutation 70: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - ReplaceComparisonOperator >= -> -1
   * Goal 47. Weak Mutation 73: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceVariable sum -> randomValue
   * Goal 48. Weak Mutation 74: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - InsertUnaryOp Negation of sum
   * Goal 49. Weak Mutation 75: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - InsertUnaryOp Negation of i
   * Goal 50. Weak Mutation 76: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - InsertUnaryOp IINC 1 i
   * Goal 51. Weak Mutation 77: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - InsertUnaryOp IINC -1 i
   * Goal 52. Weak Mutation 78: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceArithmeticOperator + -> %
   * Goal 53. Weak Mutation 79: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceArithmeticOperator + -> -
   * Goal 54. Weak Mutation 80: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceArithmeticOperator + -> *
   * Goal 55. Weak Mutation 81: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceArithmeticOperator + -> /
   * Goal 56. Weak Mutation 82: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - ReplaceVariable randomValue -> sum
   * Goal 57. Weak Mutation 83: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - InsertUnaryOp Negation of randomValue
   * Goal 58. Weak Mutation 84: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - ReplaceVariable sum -> randomValue
   * Goal 59. Weak Mutation 85: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - InsertUnaryOp Negation of sum
   * Goal 60. Weak Mutation 86: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - ReplaceComparisonOperator >= -> -1
   * Goal 61. Weak Mutation 87: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - ReplaceComparisonOperator >= -> ==
   * Goal 62. Weak Mutation 89: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:163 - InsertUnaryOp Negation of i
   * Goal 63. Weak Mutation 90: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:163 - InsertUnaryOp IINC 1 i
   * Goal 64. Weak Mutation 91: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:163 - InsertUnaryOp IINC -1 i
   */

  

  //Test case number: 1
  /*
   * 30 covered goals:
   * Goal 1. <init>(Ljava/util/List;)V_org.evosuite.runtime.mock.java.lang.MockArithmeticException_DECLARED
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Ljava/util/List;)V
   * Goal 12. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 13. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 14. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 15. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 16. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 17. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 18. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 19. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 20. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 21. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 22. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 23. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 24. Weak Mutation 15: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> >
   * Goal 25. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 26. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 27. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 28. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 29. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 30. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   */

  

  //Test case number: 2
  /*
   * 92 covered goals:
   * Goal 1. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 102
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 157
   * Goal 12. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 158
   * Goal 13. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 160
   * Goal 14. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 161
   * Goal 15. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 162
   * Goal 16. org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;: Line 163
   * Goal 17. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 182
   * Goal 18. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 187
   * Goal 19. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 189
   * Goal 20. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 190
   * Goal 21. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 193
   * Goal 22. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 23. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;
   * Goal 24. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 25. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;
   * Goal 26. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 27. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 28. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 29. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 30. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 31. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 32. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 33. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 34. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 35. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 36. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 37. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 38. Weak Mutation 14: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> ==
   * Goal 39. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 40. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 41. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 42. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 43. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 44. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   * Goal 45. Weak Mutation 64: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:158 - ReplaceConstant - 0.0 -> 1.0
   * Goal 46. Weak Mutation 65: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:158 - ReplaceConstant - 0.0 -> -1.0
   * Goal 47. Weak Mutation 66: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - ReplaceConstant - 0 -> 1
   * Goal 48. Weak Mutation 67: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - InsertUnaryOp Negation of i
   * Goal 49. Weak Mutation 68: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - InsertUnaryOp IINC 1 i
   * Goal 50. Weak Mutation 69: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - InsertUnaryOp IINC -1 i
   * Goal 51. Weak Mutation 70: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:160 - ReplaceComparisonOperator >= -> -1
   * Goal 52. Weak Mutation 73: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceVariable sum -> randomValue
   * Goal 53. Weak Mutation 74: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - InsertUnaryOp Negation of sum
   * Goal 54. Weak Mutation 75: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - InsertUnaryOp Negation of i
   * Goal 55. Weak Mutation 76: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - InsertUnaryOp IINC 1 i
   * Goal 56. Weak Mutation 77: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - InsertUnaryOp IINC -1 i
   * Goal 57. Weak Mutation 78: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceArithmeticOperator + -> %
   * Goal 58. Weak Mutation 79: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceArithmeticOperator + -> -
   * Goal 59. Weak Mutation 80: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceArithmeticOperator + -> *
   * Goal 60. Weak Mutation 81: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:161 - ReplaceArithmeticOperator + -> /
   * Goal 61. Weak Mutation 82: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - ReplaceVariable randomValue -> sum
   * Goal 62. Weak Mutation 83: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - InsertUnaryOp Negation of randomValue
   * Goal 63. Weak Mutation 84: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - ReplaceVariable sum -> randomValue
   * Goal 64. Weak Mutation 85: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - InsertUnaryOp Negation of sum
   * Goal 65. Weak Mutation 86: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:162 - ReplaceComparisonOperator >= -> -1
   * Goal 66. Weak Mutation 89: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:163 - InsertUnaryOp Negation of i
   * Goal 67. Weak Mutation 90: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:163 - InsertUnaryOp IINC 1 i
   * Goal 68. Weak Mutation 91: org.apache.commons.math3.distribution.DiscreteDistribution.sample()Ljava/lang/Object;:163 - InsertUnaryOp IINC -1 i
   * Goal 69. Weak Mutation 97: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp Negation of sampleSize
   * Goal 70. Weak Mutation 98: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp IINC 1 sampleSize
   * Goal 71. Weak Mutation 99: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp IINC -1 sampleSize
   * Goal 72. Weak Mutation 100: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - ReplaceComparisonOperator > -> -2
   * Goal 73. Weak Mutation 106: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:187 - ReplaceConstant - 0 -> 1
   * Goal 74. Weak Mutation 107: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:187 - InsertUnaryOp Negation of sampleSize
   * Goal 75. Weak Mutation 108: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:187 - InsertUnaryOp IINC 1 sampleSize
   * Goal 76. Weak Mutation 109: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:187 - InsertUnaryOp IINC -1 sampleSize
   * Goal 77. Weak Mutation 110: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - ReplaceConstant - 0 -> 1
   * Goal 78. Weak Mutation 111: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - ReplaceVariable i -> sampleSize
   * Goal 79. Weak Mutation 112: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - InsertUnaryOp Negation of i
   * Goal 80. Weak Mutation 113: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - InsertUnaryOp IINC 1 i
   * Goal 81. Weak Mutation 114: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - InsertUnaryOp IINC -1 i
   * Goal 82. Weak Mutation 115: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - ReplaceVariable sampleSize -> i
   * Goal 83. Weak Mutation 116: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - InsertUnaryOp Negation of sampleSize
   * Goal 84. Weak Mutation 117: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - InsertUnaryOp IINC 1 sampleSize
   * Goal 85. Weak Mutation 118: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - InsertUnaryOp IINC -1 sampleSize
   * Goal 86. Weak Mutation 119: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - ReplaceComparisonOperator >= -> -1
   * Goal 87. Weak Mutation 120: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - ReplaceComparisonOperator >= -> >
   * Goal 88. Weak Mutation 126: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:189 - ReplaceVariable i -> sampleSize
   * Goal 89. Weak Mutation 122: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:190 - ReplaceVariable i -> sampleSize
   * Goal 90. Weak Mutation 123: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:190 - InsertUnaryOp Negation of i
   * Goal 91. Weak Mutation 124: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:190 - InsertUnaryOp IINC 1 i
   * Goal 92. Weak Mutation 125: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:190 - InsertUnaryOp IINC -1 i
   */

  @Test public void test02()  throws Throwable  {
      DiscreteDistribution.clearORefMap();
	int[] intArray0 = new int[0];
      Well19937c well19937c0 = new Well19937c(intArray0);
      Double double0 = new Double(822.0660721701629);
      LinkedList<Pair<Byte, Double>> linkedList0 = new LinkedList<Pair<Byte, Double>>();
      Byte byte0 = new Byte((byte)0);
      Pair<Byte, Double> pair0 = new Pair<Byte, Double>(byte0, double0);
      boolean boolean0 = linkedList0.add(pair0);
      DiscreteDistribution<Byte> discreteDistribution0 = new DiscreteDistribution<Byte>((RandomGenerator) well19937c0, (List<Pair<Byte, Double>>) linkedList0);
      Byte[] byteArray0 = discreteDistribution0.sample(192);
	List obj_list_7au3e = (List) DiscreteDistribution.oref_map
			.get("sample(int)0");
	Object target_obj_7au3e = obj_list_7au3e.get(0);
	Object[] target_arr_4 = FieldPrinter.convertToObjectArray(target_obj_7au3e);
	target_obj_7au3e = target_arr_4[0];
	assertEquals(
			"(E)0,(C)org.apache.commons.math3.distribution.DiscreteDistribution,(MSIG)sample(int)0,(I)0,(A)0",
			0l, ((Byte) target_obj_7au3e).longValue());
  }

  //Test case number: 3
  /*
   * 36 covered goals:
   * Goal 1. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 102
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.reseedRandomGenerator(J)V: Line 110
   * Goal 12. org.apache.commons.math3.distribution.DiscreteDistribution.reseedRandomGenerator(J)V: Line 111
   * Goal 13. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 14. org.apache.commons.math3.distribution.DiscreteDistribution.reseedRandomGenerator(J)V
   * Goal 15. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 16. org.apache.commons.math3.distribution.DiscreteDistribution.reseedRandomGenerator(J)V
   * Goal 17. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 18. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 19. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 20. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 21. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 22. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 23. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 24. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 25. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 26. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 27. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 28. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 29. Weak Mutation 14: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> ==
   * Goal 30. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 31. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 32. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 33. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 34. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 35. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   * Goal 36. Weak Mutation 22: org.apache.commons.math3.distribution.DiscreteDistribution.reseedRandomGenerator(J)V:110 - InsertUnaryOp Negation of seed
   */

  

  //Test case number: 4
  /*
   * 62 covered goals:
   * Goal 1. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 102
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D: Line 123
   * Goal 12. org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D: Line 125
   * Goal 13. org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D: Line 126
   * Goal 14. org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D: Line 127
   * Goal 15. org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D: Line 128
   * Goal 16. org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D: Line 132
   * Goal 17. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 18. org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D
   * Goal 19. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 20. org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D
   * Goal 21. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 22. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 24. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 25. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 26. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 27. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 28. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 29. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 30. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 31. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 32. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 33. Weak Mutation 14: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> ==
   * Goal 34. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 35. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 36. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 37. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 38. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 39. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   * Goal 40. Weak Mutation 23: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:123 - ReplaceConstant - 0.0 -> 1.0
   * Goal 41. Weak Mutation 24: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:123 - ReplaceConstant - 0.0 -> -1.0
   * Goal 42. Weak Mutation 25: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:125 - ReplaceConstant - 0 -> 1
   * Goal 43. Weak Mutation 26: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:125 - InsertUnaryOp Negation of i
   * Goal 44. Weak Mutation 27: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:125 - InsertUnaryOp IINC 1 i
   * Goal 45. Weak Mutation 28: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:125 - InsertUnaryOp IINC -1 i
   * Goal 46. Weak Mutation 29: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:125 - ReplaceComparisonOperator >= -> -1
   * Goal 47. Weak Mutation 30: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:125 - ReplaceComparisonOperator >= -> >
   * Goal 48. Weak Mutation 32: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:126 - ReplaceComparisonOperator != null -> = null
   * Goal 49. Weak Mutation 37: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:126 - ReplaceComparisonOperator = null -> != null
   * Goal 50. Weak Mutation 38: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:126 - InsertUnaryOp Negation of i
   * Goal 51. Weak Mutation 39: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:126 - InsertUnaryOp IINC 1 i
   * Goal 52. Weak Mutation 40: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:126 - InsertUnaryOp IINC -1 i
   * Goal 53. Weak Mutation 41: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:127 - ReplaceComparisonOperator == -> !=
   * Goal 54. Weak Mutation 42: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:128 - InsertUnaryOp Negation of probability
   * Goal 55. Weak Mutation 43: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:128 - InsertUnaryOp Negation of i
   * Goal 56. Weak Mutation 44: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:128 - InsertUnaryOp IINC 1 i
   * Goal 57. Weak Mutation 45: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:128 - InsertUnaryOp IINC -1 i
   * Goal 58. Weak Mutation 46: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:128 - ReplaceArithmeticOperator + -> %
   * Goal 59. Weak Mutation 47: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:128 - ReplaceArithmeticOperator + -> -
   * Goal 60. Weak Mutation 48: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:128 - ReplaceArithmeticOperator + -> *
   * Goal 61. Weak Mutation 49: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:128 - ReplaceArithmeticOperator + -> /
   * Goal 62. Weak Mutation 50: org.apache.commons.math3.distribution.DiscreteDistribution.probability(Ljava/lang/Object;)D:132 - InsertUnaryOp Negation of probability
   */

  

  //Test case number: 5
  /*
   * 49 covered goals:
   * Goal 1. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 102
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;: Line 142
   * Goal 12. org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;: Line 144
   * Goal 13. org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;: Line 145
   * Goal 14. org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;: Line 148
   * Goal 15. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 16. org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;
   * Goal 17. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 18. org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;
   * Goal 19. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 20. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 22. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 23. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 24. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 25. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 26. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 27. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 28. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 29. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 30. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 31. Weak Mutation 14: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> ==
   * Goal 32. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 33. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 34. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 35. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 36. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 37. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   * Goal 38. Weak Mutation 51: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:144 - ReplaceConstant - 0 -> 1
   * Goal 39. Weak Mutation 52: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:144 - InsertUnaryOp Negation of i
   * Goal 40. Weak Mutation 53: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:144 - InsertUnaryOp IINC 1 i
   * Goal 41. Weak Mutation 54: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:144 - InsertUnaryOp IINC -1 i
   * Goal 42. Weak Mutation 55: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:144 - ReplaceComparisonOperator >= -> -1
   * Goal 43. Weak Mutation 56: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:144 - ReplaceComparisonOperator >= -> >
   * Goal 44. Weak Mutation 58: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:145 - InsertUnaryOp Negation of i
   * Goal 45. Weak Mutation 59: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:145 - InsertUnaryOp IINC 1 i
   * Goal 46. Weak Mutation 60: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:145 - InsertUnaryOp IINC -1 i
   * Goal 47. Weak Mutation 61: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:145 - InsertUnaryOp Negation of i
   * Goal 48. Weak Mutation 62: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:145 - InsertUnaryOp IINC 1 i
   * Goal 49. Weak Mutation 63: org.apache.commons.math3.distribution.DiscreteDistribution.getSamples()Ljava/util/List;:145 - InsertUnaryOp IINC -1 i
   */

  

  //Test case number: 6
  /*
   * 44 covered goals:
   * Goal 1. sample(I)[Ljava/lang/Object;_org.apache.commons.math3.exception.NumberIsTooSmallException_DECLARED
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Ljava/util/List;)V: Line 70
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 12. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 102
   * Goal 13. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 182
   * Goal 14. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 183
   * Goal 15. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 184
   * Goal 16. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Ljava/util/List;)V
   * Goal 17. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;
   * Goal 18. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Ljava/util/List;)V
   * Goal 19. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 20. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 22. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 23. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 24. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 25. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 26. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 27. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 28. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 29. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 30. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 31. Weak Mutation 14: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> ==
   * Goal 32. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 33. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 34. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 35. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 36. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 37. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   * Goal 38. Weak Mutation 97: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp Negation of sampleSize
   * Goal 39. Weak Mutation 98: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp IINC 1 sampleSize
   * Goal 40. Weak Mutation 99: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp IINC -1 sampleSize
   * Goal 41. Weak Mutation 102: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - ReplaceComparisonOperator > -> >=
   * Goal 42. Weak Mutation 103: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:183 - InsertUnaryOp Negation of sampleSize
   * Goal 43. Weak Mutation 104: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:183 - InsertUnaryOp IINC 1 sampleSize
   * Goal 44. Weak Mutation 105: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:183 - InsertUnaryOp IINC -1 sampleSize
   */

  

  //Test case number: 7
  /*
   * 43 covered goals:
   * Goal 1. sample(I)[Ljava/lang/Object;_org.apache.commons.math3.exception.NumberIsTooSmallException_DECLARED
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 102
   * Goal 12. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 182
   * Goal 13. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 183
   * Goal 14. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 184
   * Goal 15. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 16. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;
   * Goal 17. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 18. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 19. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 20. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 21. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 22. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 23. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 24. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 25. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 26. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 27. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 28. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 29. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 30. Weak Mutation 14: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> ==
   * Goal 31. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 32. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 33. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 34. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 35. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 36. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   * Goal 37. Weak Mutation 97: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp Negation of sampleSize
   * Goal 38. Weak Mutation 98: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp IINC 1 sampleSize
   * Goal 39. Weak Mutation 99: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp IINC -1 sampleSize
   * Goal 40. Weak Mutation 101: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - ReplaceComparisonOperator > -> !=
   * Goal 41. Weak Mutation 103: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:183 - InsertUnaryOp Negation of sampleSize
   * Goal 42. Weak Mutation 104: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:183 - InsertUnaryOp IINC 1 sampleSize
   * Goal 43. Weak Mutation 105: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:183 - InsertUnaryOp IINC -1 sampleSize
   */

  

  //Test case number: 8
  /*
   * 40 covered goals:
   * Goal 1. sample(I)[Ljava/lang/Object;_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 98
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 11. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 102
   * Goal 12. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 182
   * Goal 13. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;: Line 187
   * Goal 14. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 15. org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;
   * Goal 16. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 17. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 18. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 19. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 20. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 21. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 22. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 23. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 24. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 25. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 26. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 27. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 28. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 29. Weak Mutation 14: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> ==
   * Goal 30. Weak Mutation 16: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp Negation of i
   * Goal 31. Weak Mutation 17: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC 1 i
   * Goal 32. Weak Mutation 18: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:98 - InsertUnaryOp IINC -1 i
   * Goal 33. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 34. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 35. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   * Goal 36. Weak Mutation 97: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp Negation of sampleSize
   * Goal 37. Weak Mutation 98: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp IINC 1 sampleSize
   * Goal 38. Weak Mutation 99: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - InsertUnaryOp IINC -1 sampleSize
   * Goal 39. Weak Mutation 100: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:182 - ReplaceComparisonOperator > -> -2
   * Goal 40. Weak Mutation 106: org.apache.commons.math3.distribution.DiscreteDistribution.sample(I)[Ljava/lang/Object;:187 - ReplaceConstant - 0 -> 1
   */

  

  //Test case number: 9
  /*
   * 16 covered goals:
   * Goal 1. <init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V_org.evosuite.runtime.mock.java.lang.MockArithmeticException_DECLARED
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 101
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 8. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 9. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 10. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 11. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 12. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 13. Weak Mutation 6: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> >
   * Goal 14. Weak Mutation 19: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 0.0
   * Goal 15. Weak Mutation 20: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> -1.0
   * Goal 16. Weak Mutation 21: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:101 - ReplaceConstant - 1.0 -> 2.0
   */

  

  //Test case number: 10
  /*
   * 21 covered goals:
   * Goal 1. <init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V_org.apache.commons.math3.exception.NumberIsTooSmallException_DECLARED
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 96
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 11. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 12. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 13. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 14. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 15. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 16. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 17. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 18. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 19. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 20. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 21. Weak Mutation 13: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> -1
   */

  

  //Test case number: 11
  /*
   * 18 covered goals:
   * Goal 1. <init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V
   * Goal 10. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 11. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 12. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 13. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 14. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 15. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 16. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 17. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 18. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   */

  

  //Test case number: 12
  /*
   * 22 covered goals:
   * Goal 1. <init>(Ljava/util/List;)V_org.apache.commons.math3.exception.NumberIsTooSmallException_DECLARED
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 90
   * Goal 5. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 92
   * Goal 6. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 93
   * Goal 7. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 94
   * Goal 8. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 95
   * Goal 9. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 96
   * Goal 10. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Ljava/util/List;)V
   * Goal 11. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   * Goal 12. Weak Mutation 1: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceConstant - 0 -> 1
   * Goal 13. Weak Mutation 2: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp Negation of i
   * Goal 14. Weak Mutation 3: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC 1 i
   * Goal 15. Weak Mutation 4: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - InsertUnaryOp IINC -1 i
   * Goal 16. Weak Mutation 5: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:92 - ReplaceComparisonOperator >= -> -1
   * Goal 17. Weak Mutation 8: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp Negation of i
   * Goal 18. Weak Mutation 9: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC 1 i
   * Goal 19. Weak Mutation 10: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:93 - InsertUnaryOp IINC -1 i
   * Goal 20. Weak Mutation 11: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> 1.0
   * Goal 21. Weak Mutation 12: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceConstant - 0.0 -> -1.0
   * Goal 22. Weak Mutation 13: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:95 - ReplaceComparisonOperator >= -> -1
   */

  

  //Test case number: 13
  /*
   * 5 covered goals:
   * Goal 1. <init>(Ljava/util/List;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 87
   * Goal 3. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V: Line 89
   * Goal 4. org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Ljava/util/List;)V
   * Goal 5. Weak Mutation 0: org.apache.commons.math3.distribution.DiscreteDistribution.<init>(Lorg/apache/commons/math3/random/RandomGenerator;Ljava/util/List;)V:87 - ReplaceVariable rng -> random
   */
}
