/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 10 01:24:29 GMT 2017
 */

package org.jfree.chart.axis;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.LegendItemSource;
import org.jfree.chart.axis.Axis;
import org.jfree.chart.axis.AxisCollection;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryAxis3D;
import org.jfree.chart.axis.CyclicNumberAxis;
import org.jfree.chart.axis.ModuloAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.PeriodAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.block.Arrangement;
import org.jfree.chart.block.ColumnArrangement;
import org.jfree.chart.plot.CombinedDomainCategoryPlot;
import org.jfree.chart.plot.CombinedRangeCategoryPlot;
import org.jfree.chart.plot.CombinedRangeXYPlot;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.ThermometerPlot;
import org.jfree.chart.title.LegendTitle;
import org.jfree.chart.util.HorizontalAlignment;
import org.jfree.chart.util.RectangleEdge;
import org.jfree.chart.util.VerticalAlignment;
import org.jfree.data.Range;
import org.junit.runner.RunWith;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.lang.reflect.Field;
import org.apache.commons.lang3.reflect.FieldUtils;
import static org.junit.Assert.*;
import myprinter.FieldPrinter;

public class DiffTGenTest0 {

  //Test case number: 0
  /*
   * 10 covered goals:
   * Goal 1. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 6. org.jfree.chart.axis.AxisCollection.getAxesAtTop()Ljava/util/List;: Line 85
   * Goal 7. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 8. org.jfree.chart.axis.AxisCollection.getAxesAtTop()Ljava/util/List;
   * Goal 9. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 10. org.jfree.chart.axis.AxisCollection.getAxesAtTop()Ljava/util/List;
   */

  

  //Test case number: 1
  /*
   * 10 covered goals:
   * Goal 1. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 6. org.jfree.chart.axis.AxisCollection.getAxesAtRight()Ljava/util/List;: Line 115
   * Goal 7. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 8. org.jfree.chart.axis.AxisCollection.getAxesAtRight()Ljava/util/List;
   * Goal 9. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 10. org.jfree.chart.axis.AxisCollection.getAxesAtRight()Ljava/util/List;
   */

  

  //Test case number: 2
  /*
   * 10 covered goals:
   * Goal 1. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 6. org.jfree.chart.axis.AxisCollection.getAxesAtLeft()Ljava/util/List;: Line 105
   * Goal 7. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 8. org.jfree.chart.axis.AxisCollection.getAxesAtLeft()Ljava/util/List;
   * Goal 9. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 10. org.jfree.chart.axis.AxisCollection.getAxesAtLeft()Ljava/util/List;
   */

  

  //Test case number: 3
  /*
   * 10 covered goals:
   * Goal 1. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 6. org.jfree.chart.axis.AxisCollection.getAxesAtBottom()Ljava/util/List;: Line 95
   * Goal 7. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 8. org.jfree.chart.axis.AxisCollection.getAxesAtBottom()Ljava/util/List;
   * Goal 9. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 10. org.jfree.chart.axis.AxisCollection.getAxesAtBottom()Ljava/util/List;
   */

  

  //Test case number: 4
  /*
   * 28 covered goals:
   * Goal 1. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 6. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 126
   * Goal 7. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 129
   * Goal 8. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 132
   * Goal 9. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 133
   * Goal 10. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 136
   * Goal 11. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 139
   * Goal 12. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 142
   * Goal 13. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 143
   * Goal 14. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 146
   * Goal 15. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 16. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 17. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 18. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 19. Weak Mutation 0: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:126 - ReplaceComparisonOperator != null -> = null
   * Goal 20. Weak Mutation 3: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:129 - ReplaceComparisonOperator != null -> = null
   * Goal 21. Weak Mutation 6: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> 0
   * Goal 22. Weak Mutation 7: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> 1
   * Goal 23. Weak Mutation 8: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> -2
   * Goal 24. Weak Mutation 11: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceComparisonOperator == -> <=
   * Goal 25. Weak Mutation 12: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:133 - ReplaceComparisonOperator != -> ==
   * Goal 26. Weak Mutation 13: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:136 - ReplaceComparisonOperator != -> ==
   * Goal 27. Weak Mutation 14: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:139 - ReplaceComparisonOperator != -> ==
   * Goal 28. Weak Mutation 15: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:142 - ReplaceComparisonOperator != -> ==
   */

  @Test public void test4()  throws Throwable  {
      AxisCollection.clearORefMap();
	AxisCollection axisCollection0 = new AxisCollection();
      ThermometerPlot thermometerPlot0 = new ThermometerPlot();
      NumberAxis numberAxis0 = (NumberAxis)thermometerPlot0.getRangeAxis();
      CombinedRangeCategoryPlot combinedRangeCategoryPlot0 = new CombinedRangeCategoryPlot((ValueAxis) numberAxis0);
      RectangleEdge rectangleEdge0 = combinedRangeCategoryPlot0.getRangeAxisEdge((-1503));
      axisCollection0.add(numberAxis0, rectangleEdge0);
	List obj_list_7au3e = (List) AxisCollection.oref_map
			.get("add(Axis$RectangleEdge)0");
	Object target_obj_7au3e = obj_list_7au3e.get(1);
	Field[] target_fields_4 = FieldUtils.getAllFields(target_obj_7au3e
			.getClass());
	target_obj_7au3e = FieldUtils.readField(target_fields_4[5],
			target_obj_7au3e, true);
	List target_list_5 = (List) target_obj_7au3e;
	target_obj_7au3e = target_list_5.get(0);
	Field[] target_fields_6 = FieldUtils.getAllFields(target_obj_7au3e
			.getClass());
	target_obj_7au3e = FieldUtils.readField(target_fields_6[8],
			target_obj_7au3e, true);
	Field[] target_fields_7 = FieldUtils.getAllFields(target_obj_7au3e
			.getClass());
	target_obj_7au3e = FieldUtils.readField(target_fields_7[3],
			target_obj_7au3e, true);
	assertEquals(
			"(E)0,(C)org.jfree.chart.axis.AxisCollection,(MSIG)add(Axis$RectangleEdge)0,(I)1,(F)5,(L)0,(F)8,(F)3",
			1.0d, ((Double) target_obj_7au3e).doubleValue(), 1e-12);
  }

  //Test case number: 5
  /*
   * 24 covered goals:
   * Goal 1. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 6. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 126
   * Goal 7. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 129
   * Goal 8. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 132
   * Goal 9. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 133
   * Goal 10. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 136
   * Goal 11. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 137
   * Goal 12. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 146
   * Goal 13. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 14. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 15. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 16. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 17. Weak Mutation 0: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:126 - ReplaceComparisonOperator != null -> = null
   * Goal 18. Weak Mutation 3: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:129 - ReplaceComparisonOperator != null -> = null
   * Goal 19. Weak Mutation 6: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> 0
   * Goal 20. Weak Mutation 7: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> 1
   * Goal 21. Weak Mutation 8: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> -2
   * Goal 22. Weak Mutation 11: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceComparisonOperator == -> <=
   * Goal 23. Weak Mutation 12: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:133 - ReplaceComparisonOperator != -> ==
   * Goal 24. Weak Mutation 13: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:136 - ReplaceComparisonOperator != -> ==
   */

  //Test case number: 6
  /*
   * 26 covered goals:
   * Goal 1. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 6. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 126
   * Goal 7. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 129
   * Goal 8. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 132
   * Goal 9. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 133
   * Goal 10. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 136
   * Goal 11. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 139
   * Goal 12. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 140
   * Goal 13. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 146
   * Goal 14. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 15. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 16. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 17. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 18. Weak Mutation 0: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:126 - ReplaceComparisonOperator != null -> = null
   * Goal 19. Weak Mutation 3: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:129 - ReplaceComparisonOperator != null -> = null
   * Goal 20. Weak Mutation 6: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> 0
   * Goal 21. Weak Mutation 7: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> 1
   * Goal 22. Weak Mutation 8: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> -2
   * Goal 23. Weak Mutation 11: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceComparisonOperator == -> <=
   * Goal 24. Weak Mutation 12: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:133 - ReplaceComparisonOperator != -> ==
   * Goal 25. Weak Mutation 13: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:136 - ReplaceComparisonOperator != -> ==
   * Goal 26. Weak Mutation 14: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:139 - ReplaceComparisonOperator != -> ==
   */

  //Test case number: 7
  /*
   * 16 covered goals:
   * Goal 1. add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 6. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 7. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 126
   * Goal 8. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 129
   * Goal 9. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 130
   * Goal 10. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 11. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 12. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 13. Weak Mutation 0: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:126 - ReplaceComparisonOperator != null -> = null
   * Goal 14. Weak Mutation 3: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:129 - ReplaceComparisonOperator != null -> = null
   * Goal 15. Weak Mutation 4: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:130 - ReplaceConstant - Null 'edge' argument. -> 
   * Goal 16. Weak Mutation 5: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:130 - ReplaceComparisonOperator == -> !=
   */

  

  //Test case number: 8
  /*
   * 22 covered goals:
   * Goal 1. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 6. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 126
   * Goal 7. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 129
   * Goal 8. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 132
   * Goal 9. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 133
   * Goal 10. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 134
   * Goal 11. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 146
   * Goal 12. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 13. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 14. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 15. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 16. Weak Mutation 0: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:126 - ReplaceComparisonOperator != null -> = null
   * Goal 17. Weak Mutation 3: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:129 - ReplaceComparisonOperator != null -> = null
   * Goal 18. Weak Mutation 6: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> 0
   * Goal 19. Weak Mutation 7: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> 1
   * Goal 20. Weak Mutation 8: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceConstant - -1 -> -2
   * Goal 21. Weak Mutation 11: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:132 - ReplaceComparisonOperator == -> <=
   * Goal 22. Weak Mutation 12: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:133 - ReplaceComparisonOperator != -> ==
   */

  //Test case number: 9
  /*
   * 14 covered goals:
   * Goal 1. add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 2. org.jfree.chart.axis.AxisCollection.<init>()V: Line 72
   * Goal 3. org.jfree.chart.axis.AxisCollection.<init>()V: Line 73
   * Goal 4. org.jfree.chart.axis.AxisCollection.<init>()V: Line 74
   * Goal 5. org.jfree.chart.axis.AxisCollection.<init>()V: Line 75
   * Goal 6. org.jfree.chart.axis.AxisCollection.<init>()V: Line 76
   * Goal 7. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 126
   * Goal 8. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V: Line 127
   * Goal 9. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 10. org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V
   * Goal 11. org.jfree.chart.axis.AxisCollection.<init>()V
   * Goal 12. Weak Mutation 0: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:126 - ReplaceComparisonOperator != null -> = null
   * Goal 13. Weak Mutation 1: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:127 - ReplaceConstant - Null 'axis' argument. -> 
   * Goal 14. Weak Mutation 2: org.jfree.chart.axis.AxisCollection.add(Lorg/jfree/chart/axis/Axis;Lorg/jfree/chart/util/RectangleEdge;)V:127 - ReplaceComparisonOperator == -> !=
   */
}
