/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 31 22:38:10 GMT 2017
 */

package org.jfree.chart.plot;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.Stroke;
import java.awt.SystemColor;
import java.awt.geom.Arc2D;
import java.awt.geom.Area;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.annotations.XYTextAnnotation;
import org.jfree.chart.entity.EntityCollection;
import org.jfree.chart.entity.StandardEntityCollection;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotRenderingInfo;
import org.jfree.chart.plot.PlotState;
import org.jfree.chart.util.TableOrder;
import org.jfree.data.DefaultKeyedValues;
import org.jfree.data.KeyedValues;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.CategoryToPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultKeyedValuesDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.junit.runner.RunWith;
import sun.java2d.SunGraphics2D;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.lang.reflect.Field;
import org.apache.commons.lang3.reflect.FieldUtils;
import static org.junit.Assert.*;
import myprinter.FieldPrinter;

public class DiffTGen0Test {

  //Test case number: 0
  /*
   * 54 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V: Line 231
   * Goal 6. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 621
   * Goal 7. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 629
   * Goal 8. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 630
   * Goal 9. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 631
   * Goal 10. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 633
   * Goal 11. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 636
   * Goal 12. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 806
   * Goal 13. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 970
   * Goal 14. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z: Line 191
   * Goal 15. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 16. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 17. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 18. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 19. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 20. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 21. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 22. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 23. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 24. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 25. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 26. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 27. Weak Mutation 21: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 28: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:621 - ReplaceComparisonOperator == -> !=
   * Goal 29. Weak Mutation 44: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> extent
   * Goal 30. Weak Mutation 45: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_INTERIOR_GAP
   * Goal 31. Weak Mutation 46: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> MAX_INTERIOR_GAP
   * Goal 32. Weak Mutation 47: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_START_ANGLE
   * Goal 33. Weak Mutation 48: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 34. Weak Mutation 49: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of start
   * Goal 35. Weak Mutation 50: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> start
   * Goal 36. Weak Mutation 51: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_INTERIOR_GAP
   * Goal 37. Weak Mutation 52: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> MAX_INTERIOR_GAP
   * Goal 38. Weak Mutation 53: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_START_ANGLE
   * Goal 39. Weak Mutation 54: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 40. Weak Mutation 55: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of extent
   * Goal 41. Weak Mutation 56: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> %
   * Goal 42. Weak Mutation 59: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> /
   * Goal 43. Weak Mutation 60: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_LABEL_OUTLINE_STROKE
   * Goal 44. Weak Mutation 61: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_OUTLINE_STROKE
   * Goal 45. Weak Mutation 62: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> start
   * Goal 46. Weak Mutation 63: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_INTERIOR_GAP
   * Goal 47. Weak Mutation 64: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> end
   * Goal 48. Weak Mutation 65: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> MAX_INTERIOR_GAP
   * Goal 49. Weak Mutation 66: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_START_ANGLE
   * Goal 50. Weak Mutation 67: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 51. Weak Mutation 68: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - InsertUnaryOp Negation of extent
   * Goal 52. Weak Mutation 69: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceConstant - 0.0 -> 1.0
   * Goal 53. Weak Mutation 70: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceConstant - 0.0 -> -1.0
   * Goal 54. Weak Mutation 73: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceComparisonOperator >= -> >
   */

  @Test public void test00()  throws Throwable  {
      PiePlot3D.clearORefMap();
	Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double();
      DefaultPieDataset defaultPieDataset0 = new DefaultPieDataset();
      PiePlot3D piePlot3D0 = new PiePlot3D((PieDataset) defaultPieDataset0);
      Font font0 = XYTextAnnotation.DEFAULT_FONT;
      JFreeChart jFreeChart0 = new JFreeChart("Pie_3D_Plot", font0, (Plot) piePlot3D0, false);
      ChartRenderingInfo chartRenderingInfo0 = new ChartRenderingInfo();
      BufferedImage bufferedImage0 = jFreeChart0.createBufferedImage(804, 804, chartRenderingInfo0);
      SunGraphics2D sunGraphics2D0 = (SunGraphics2D)bufferedImage0.createGraphics();
      Arc2D.Double arc2D_Double0 = new Arc2D.Double(1.0, (double) 1, (-677.3), (-677.3), 0.6129547874142126, (double) 0, 0);
      Area area0 = new Area();
      SystemColor systemColor0 = SystemColor.activeCaptionBorder;
      piePlot3D0.drawSide(sunGraphics2D0, rectangle2D_Double0, arc2D_Double0, area0, area0, sunGraphics2D0.backgroundColor, systemColor0, sunGraphics2D0.stroke, false, false);
	List obj_list_7au3e = (List) PiePlot3D.oref_map
			.get("draw(Graphics2D$Rectangle2D$Point2D$PlotState$PlotRenderingInfo)0");
	Object target_obj_7au3e = obj_list_7au3e.get(2);
	Field[] target_fields_4 = FieldUtils.getAllFields(target_obj_7au3e
			.getClass());
	target_obj_7au3e = FieldUtils.readField(target_fields_4[23],
			target_obj_7au3e, true);
	assertEquals(
			"(E)0,(C)org.jfree.chart.plot.PiePlot3D,(MSIG)draw(Graphics2D$Rectangle2D$Point2D$PlotState$PlotRenderingInfo)0,(I)2,(F)23",
			-8355712l, ((Integer) target_obj_7au3e).longValue());
  }

  //Test case number: 1
  /*
   * 53 covered goals:
   * Goal 1. drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V: Line 231
   * Goal 7. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 621
   * Goal 8. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 622
   * Goal 9. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 623
   * Goal 10. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 624
   * Goal 11. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 625
   * Goal 12. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 629
   * Goal 13. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z: Line 191
   * Goal 14. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 208
   * Goal 15. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 209
   * Goal 16. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 210
   * Goal 17. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 18. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 19. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 20. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 21. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 22. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 23. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 24. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 25. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 26. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 27. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 28. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 29. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 30. Weak Mutation 18: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_INTERIOR
   * Goal 31. Weak Mutation 19: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_PIE_AREA
   * Goal 32. Weak Mutation 20: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_LINK_AREA
   * Goal 33. Weak Mutation 21: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - InsertUnaryOp Negation
   * Goal 34. Weak Mutation 22: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_INTERIOR
   * Goal 35. Weak Mutation 23: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_PIE_AREA
   * Goal 36. Weak Mutation 24: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_LINK_AREA
   * Goal 37. Weak Mutation 25: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp Negation of darker
   * Goal 38. Weak Mutation 26: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC 1 darker
   * Goal 39. Weak Mutation 27: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC -1 darker
   * Goal 40. Weak Mutation 28: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:621 - ReplaceComparisonOperator == -> !=
   * Goal 41. Weak Mutation 29: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_BACKGROUND_PAINT
   * Goal 42. Weak Mutation 30: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_SHADOW_PAINT
   * Goal 43. Weak Mutation 32: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_OUTLINE_PAINT
   * Goal 44. Weak Mutation 33: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_OUTLINE_PAINT
   * Goal 45. Weak Mutation 34: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_PAINT
   * Goal 46. Weak Mutation 35: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_BACKGROUND_PAINT
   * Goal 47. Weak Mutation 36: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceComparisonOperator == -> !=
   * Goal 48. Weak Mutation 37: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_LABEL_BACKGROUND_PAINT
   * Goal 49. Weak Mutation 38: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_LABEL_SHADOW_PAINT
   * Goal 50. Weak Mutation 40: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_OUTLINE_PAINT
   * Goal 51. Weak Mutation 41: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_LABEL_OUTLINE_PAINT
   * Goal 52. Weak Mutation 42: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_LABEL_PAINT
   * Goal 53. Weak Mutation 43: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_BACKGROUND_PAINT
   */

  //Test case number: 2
  /*
   * 73 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V: Line 231
   * Goal 6. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 621
   * Goal 7. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 622
   * Goal 8. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 629
   * Goal 9. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 630
   * Goal 10. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 631
   * Goal 11. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 633
   * Goal 12. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 636
   * Goal 13. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 806
   * Goal 14. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 970
   * Goal 15. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z: Line 191
   * Goal 16. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 208
   * Goal 17. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 209
   * Goal 18. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 210
   * Goal 19. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 20. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 21. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 22. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 23. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 24. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 25. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 26. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 27. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 28. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 29. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 30. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 31. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 32. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 33. Weak Mutation 18: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_INTERIOR
   * Goal 34. Weak Mutation 19: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_PIE_AREA
   * Goal 35. Weak Mutation 20: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_LINK_AREA
   * Goal 36. Weak Mutation 21: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - InsertUnaryOp Negation
   * Goal 37. Weak Mutation 22: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_INTERIOR
   * Goal 38. Weak Mutation 23: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_PIE_AREA
   * Goal 39. Weak Mutation 24: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_LINK_AREA
   * Goal 40. Weak Mutation 25: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp Negation of darker
   * Goal 41. Weak Mutation 26: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC 1 darker
   * Goal 42. Weak Mutation 27: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC -1 darker
   * Goal 43. Weak Mutation 28: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:621 - ReplaceComparisonOperator == -> !=
   * Goal 44. Weak Mutation 29: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_BACKGROUND_PAINT
   * Goal 45. Weak Mutation 30: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_SHADOW_PAINT
   * Goal 46. Weak Mutation 31: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> outlinePaint
   * Goal 47. Weak Mutation 32: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_OUTLINE_PAINT
   * Goal 48. Weak Mutation 33: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_OUTLINE_PAINT
   * Goal 49. Weak Mutation 34: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_PAINT
   * Goal 50. Weak Mutation 35: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_BACKGROUND_PAINT
   * Goal 51. Weak Mutation 36: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceComparisonOperator == -> !=
   * Goal 52. Weak Mutation 45: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_INTERIOR_GAP
   * Goal 53. Weak Mutation 46: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> MAX_INTERIOR_GAP
   * Goal 54. Weak Mutation 47: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_START_ANGLE
   * Goal 55. Weak Mutation 48: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 56. Weak Mutation 49: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of start
   * Goal 57. Weak Mutation 51: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_INTERIOR_GAP
   * Goal 58. Weak Mutation 52: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> MAX_INTERIOR_GAP
   * Goal 59. Weak Mutation 53: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_START_ANGLE
   * Goal 60. Weak Mutation 54: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 61. Weak Mutation 55: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of extent
   * Goal 62. Weak Mutation 56: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> %
   * Goal 63. Weak Mutation 59: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> /
   * Goal 64. Weak Mutation 60: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_LABEL_OUTLINE_STROKE
   * Goal 65. Weak Mutation 61: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_OUTLINE_STROKE
   * Goal 66. Weak Mutation 63: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_INTERIOR_GAP
   * Goal 67. Weak Mutation 65: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> MAX_INTERIOR_GAP
   * Goal 68. Weak Mutation 66: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_START_ANGLE
   * Goal 69. Weak Mutation 67: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 70. Weak Mutation 68: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - InsertUnaryOp Negation of extent
   * Goal 71. Weak Mutation 69: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceConstant - 0.0 -> 1.0
   * Goal 72. Weak Mutation 70: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceConstant - 0.0 -> -1.0
   * Goal 73. Weak Mutation 73: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceComparisonOperator >= -> >
   */

  //Test case number: 3
  /*
   * 18 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z: Line 191
   * Goal 6. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 7. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z
   * Goal 8. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 9. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z
   * Goal 10. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 11. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 12. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 13. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 14. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 15. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 21: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - InsertUnaryOp Negation
   */

  

  //Test case number: 4
  /*
   * 17 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V: Line 231
   * Goal 6. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 7. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V
   * Goal 8. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 9. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V
   * Goal 10. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 11. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 12. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 13. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 14. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 15. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   */

  //Test case number: 5
  /*
   * 25 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>()V: Line 142
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V: Line 175
   * Goal 7. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V: Line 176
   * Goal 8. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V: Line 177
   * Goal 9. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 10. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V
   * Goal 11. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 12. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V
   * Goal 13. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 14. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 15. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 16. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 17. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 18. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 19. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 20. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 13: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - ReplaceVariable factor -> DEFAULT_INTERIOR_GAP
   * Goal 22. Weak Mutation 14: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - ReplaceVariable factor -> MAX_INTERIOR_GAP
   * Goal 23. Weak Mutation 15: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - ReplaceVariable factor -> DEFAULT_START_ANGLE
   * Goal 24. Weak Mutation 16: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - ReplaceVariable factor -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 25. Weak Mutation 17: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - InsertUnaryOp Negation of factor
   */

  

  //Test case number: 6
  /*
   * 18 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1015
   * Goal 6. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1016
   * Goal 7. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 8. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 9. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 10. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 11. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 12. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 13. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 14. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 15. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 153: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1015 - ReplaceComparisonOperator != -> ==
   * Goal 18. Weak Mutation 154: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1016 - ReplaceConstant - 1 -> 0
   */

  

  //Test case number: 7
  /*
   * 22 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1015
   * Goal 6. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1018
   * Goal 7. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1019
   * Goal 8. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 9. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z
   * Goal 10. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 11. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z
   * Goal 12. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 13. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 14. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 15. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 16. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 17. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 19. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 20. Weak Mutation 153: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1015 - ReplaceComparisonOperator != -> ==
   * Goal 21. Weak Mutation 155: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1018 - ReplaceComparisonOperator != -> ==
   * Goal 22. Weak Mutation 156: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1019 - ReplaceConstant - 0 -> 1
   */

  

  //Test case number: 8
  /*
   * 79 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V: Line 231
   * Goal 6. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 621
   * Goal 7. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 622
   * Goal 8. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 623
   * Goal 9. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 624
   * Goal 10. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 625
   * Goal 11. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 629
   * Goal 12. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 630
   * Goal 13. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 631
   * Goal 14. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 633
   * Goal 15. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 636
   * Goal 16. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 806
   * Goal 17. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 970
   * Goal 18. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z: Line 191
   * Goal 19. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 208
   * Goal 20. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 209
   * Goal 21. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 210
   * Goal 22. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 23. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 24. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 25. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 26. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 27. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 28. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 29. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 30. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 31. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 32. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 33. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 34. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 35. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 36. Weak Mutation 18: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_INTERIOR
   * Goal 37. Weak Mutation 19: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_PIE_AREA
   * Goal 38. Weak Mutation 20: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_LINK_AREA
   * Goal 39. Weak Mutation 21: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - InsertUnaryOp Negation
   * Goal 40. Weak Mutation 22: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_INTERIOR
   * Goal 41. Weak Mutation 23: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_PIE_AREA
   * Goal 42. Weak Mutation 24: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_LINK_AREA
   * Goal 43. Weak Mutation 25: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp Negation of darker
   * Goal 44. Weak Mutation 26: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC 1 darker
   * Goal 45. Weak Mutation 27: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC -1 darker
   * Goal 46. Weak Mutation 28: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:621 - ReplaceComparisonOperator == -> !=
   * Goal 47. Weak Mutation 29: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_BACKGROUND_PAINT
   * Goal 48. Weak Mutation 30: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_LABEL_SHADOW_PAINT
   * Goal 49. Weak Mutation 31: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> outlinePaint
   * Goal 50. Weak Mutation 32: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_OUTLINE_PAINT
   * Goal 51. Weak Mutation 35: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceVariable paint -> DEFAULT_BACKGROUND_PAINT
   * Goal 52. Weak Mutation 36: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:622 - ReplaceComparisonOperator == -> !=
   * Goal 53. Weak Mutation 37: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_LABEL_BACKGROUND_PAINT
   * Goal 54. Weak Mutation 38: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_LABEL_SHADOW_PAINT
   * Goal 55. Weak Mutation 39: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> outlinePaint
   * Goal 56. Weak Mutation 40: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_OUTLINE_PAINT
   * Goal 57. Weak Mutation 43: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:623 - ReplaceVariable paint -> DEFAULT_BACKGROUND_PAINT
   * Goal 58. Weak Mutation 45: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_INTERIOR_GAP
   * Goal 59. Weak Mutation 46: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> MAX_INTERIOR_GAP
   * Goal 60. Weak Mutation 47: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_START_ANGLE
   * Goal 61. Weak Mutation 48: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 62. Weak Mutation 49: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of start
   * Goal 63. Weak Mutation 51: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_INTERIOR_GAP
   * Goal 64. Weak Mutation 52: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> MAX_INTERIOR_GAP
   * Goal 65. Weak Mutation 53: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_START_ANGLE
   * Goal 66. Weak Mutation 54: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 67. Weak Mutation 55: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of extent
   * Goal 68. Weak Mutation 56: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> %
   * Goal 69. Weak Mutation 59: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> /
   * Goal 70. Weak Mutation 60: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_LABEL_OUTLINE_STROKE
   * Goal 71. Weak Mutation 61: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_OUTLINE_STROKE
   * Goal 72. Weak Mutation 63: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_INTERIOR_GAP
   * Goal 73. Weak Mutation 65: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> MAX_INTERIOR_GAP
   * Goal 74. Weak Mutation 66: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_START_ANGLE
   * Goal 75. Weak Mutation 67: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceVariable extent -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 76. Weak Mutation 68: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - InsertUnaryOp Negation of extent
   * Goal 77. Weak Mutation 69: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceConstant - 0.0 -> 1.0
   * Goal 78. Weak Mutation 70: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceConstant - 0.0 -> -1.0
   * Goal 79. Weak Mutation 73: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:636 - ReplaceComparisonOperator >= -> >
   */

  //Test case number: 9
  /*
   * 23 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>()V: Line 142
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.getDepthFactor()D: Line 163
   * Goal 7. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 8. org.jfree.chart.plot.PiePlot3D.getDepthFactor()D
   * Goal 9. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 10. org.jfree.chart.plot.PiePlot3D.getDepthFactor()D
   * Goal 11. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 12. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 13. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 14. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 15. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 16. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 19. Weak Mutation 8: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - ReplaceVariable depthFactor -> DEFAULT_INTERIOR_GAP
   * Goal 20. Weak Mutation 9: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - ReplaceVariable depthFactor -> MAX_INTERIOR_GAP
   * Goal 21. Weak Mutation 10: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - ReplaceVariable depthFactor -> DEFAULT_START_ANGLE
   * Goal 22. Weak Mutation 11: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - ReplaceVariable depthFactor -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 23. Weak Mutation 12: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - InsertUnaryOp Negation
   */

  

  //Test case number: 10
  /*
   * 18 covered goals:
   * Goal 1. getPlotType()Ljava/lang/String;_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.getPlotType()Ljava/lang/String;: Line 978
   * Goal 7. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 8. org.jfree.chart.plot.PiePlot3D.getPlotType()Ljava/lang/String;
   * Goal 9. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 10. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 11. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 12. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 13. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 14. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 15. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 128: org.jfree.chart.plot.PiePlot3D.getPlotType()Ljava/lang/String;:978 - ReplaceConstant - Pie_3D_Plot -> 
   */

  

  //Test case number: 11
  /*
   * 42 covered goals:
   * Goal 1. drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 621
   * Goal 7. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 629
   * Goal 8. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 630
   * Goal 9. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 631
   * Goal 10. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 633
   * Goal 11. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z: Line 191
   * Goal 12. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 13. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 14. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 15. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 16. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 17. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 18. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 19. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 20. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 22. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 21: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - InsertUnaryOp Negation
   * Goal 24. Weak Mutation 28: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:621 - ReplaceComparisonOperator == -> !=
   * Goal 25. Weak Mutation 44: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> extent
   * Goal 26. Weak Mutation 45: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_INTERIOR_GAP
   * Goal 27. Weak Mutation 46: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> MAX_INTERIOR_GAP
   * Goal 28. Weak Mutation 47: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_START_ANGLE
   * Goal 29. Weak Mutation 48: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 30. Weak Mutation 49: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of start
   * Goal 31. Weak Mutation 50: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> start
   * Goal 32. Weak Mutation 51: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_INTERIOR_GAP
   * Goal 33. Weak Mutation 52: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> MAX_INTERIOR_GAP
   * Goal 34. Weak Mutation 53: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_START_ANGLE
   * Goal 35. Weak Mutation 54: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 36. Weak Mutation 55: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of extent
   * Goal 37. Weak Mutation 56: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> %
   * Goal 38. Weak Mutation 57: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> -
   * Goal 39. Weak Mutation 58: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> *
   * Goal 40. Weak Mutation 59: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> /
   * Goal 41. Weak Mutation 60: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_LABEL_OUTLINE_STROKE
   * Goal 42. Weak Mutation 61: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_OUTLINE_STROKE
   */
}
