/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 31 22:24:56 GMT 2017
 */

package org.joda.time.field;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockGregorianCalendar;
import org.joda.time.Chronology;
import org.joda.time.DateTimeField;
import org.joda.time.DateTimeFieldType;
import org.joda.time.DateTimeZone;
import org.joda.time.DurationField;
import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;
import org.joda.time.LocalTime;
import org.joda.time.ReadablePartial;
import org.joda.time.chrono.BuddhistChronology;
import org.joda.time.field.DividedDateTimeField;
import org.joda.time.field.RemainderDateTimeField;
import org.joda.time.field.TestBaseDateTimeField;
import org.joda.time.field.TestPreciseDateTimeField;
import org.joda.time.field.ZeroIsMaxDateTimeField;
import org.joda.time.tz.FixedDateTimeZone;
import org.junit.runner.RunWith;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.lang.reflect.Field;
import org.apache.commons.lang3.reflect.FieldUtils;
import static org.junit.Assert.*;
import myprinter.FieldPrinter;

public class DiffTGen0Test {

  //Test case number: 0
  /*
   * 18 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 53
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 54
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 57
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I
   * Goal 8. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 9. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I
   * Goal 10. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 11. Weak Mutation 5: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:53 - InsertUnaryOp Negation of instant
   * Goal 12. Weak Mutation 6: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp Negation of value
   * Goal 13. Weak Mutation 7: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp IINC 1 value
   * Goal 14. Weak Mutation 8: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp IINC -1 value
   * Goal 15. Weak Mutation 11: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - ReplaceComparisonOperator != -> >
   * Goal 16. Weak Mutation 12: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp Negation of value
   * Goal 17. Weak Mutation 13: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp IINC 1 value
   * Goal 18. Weak Mutation 14: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp IINC -1 value
   */

  

  //Test case number: 1
  /*
   * 18 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 53
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 54
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 57
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I
   * Goal 8. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 9. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I
   * Goal 10. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 11. Weak Mutation 5: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:53 - InsertUnaryOp Negation of instant
   * Goal 12. Weak Mutation 6: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp Negation of value
   * Goal 13. Weak Mutation 7: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp IINC 1 value
   * Goal 14. Weak Mutation 8: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp IINC -1 value
   * Goal 15. Weak Mutation 10: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - ReplaceComparisonOperator != -> <
   * Goal 16. Weak Mutation 12: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp Negation of value
   * Goal 17. Weak Mutation 13: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp IINC 1 value
   * Goal 18. Weak Mutation 14: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp IINC -1 value
   */

  

  //Test case number: 2
  /*
   * 7 covered goals:
   * Goal 1. <init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 48
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. Weak Mutation 1: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> >=
   * Goal 6. Weak Mutation 3: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:48 - ReplaceConstant - Wrapped field's minumum value must be zero -> 
   * Goal 7. Weak Mutation 4: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:48 - ReplaceComparisonOperator == -> !=
   */

  

  //Test case number: 3
  /*
   * 12 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I: Line 77
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 35: org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I:77 - ReplaceVariable minuendInstant -> subtrahendInstant
   * Goal 10. Weak Mutation 36: org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I:77 - InsertUnaryOp Negation of minuendInstant
   * Goal 11. Weak Mutation 37: org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I:77 - ReplaceVariable subtrahendInstant -> minuendInstant
   * Goal 12. Weak Mutation 38: org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I:77 - InsertUnaryOp Negation of subtrahendInstant
   */

  

  //Test case number: 4
  /*
   * 16 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I: Line 73
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 27: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - ReplaceVariable fieldIndex -> valueToAdd
   * Goal 10. Weak Mutation 28: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp Negation of fieldIndex
   * Goal 11. Weak Mutation 29: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp IINC 1 fieldIndex
   * Goal 12. Weak Mutation 30: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp IINC -1 fieldIndex
   * Goal 13. Weak Mutation 31: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - ReplaceVariable valueToAdd -> fieldIndex
   * Goal 14. Weak Mutation 32: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp Negation of valueToAdd
   * Goal 15. Weak Mutation 33: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp IINC 1 valueToAdd
   * Goal 16. Weak Mutation 34: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp IINC -1 valueToAdd
   */

  

  //Test case number: 5
  /*
   * 12 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J: Line 65
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 19: org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J:65 - ReplaceVariable instant -> value
   * Goal 10. Weak Mutation 20: org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J:65 - InsertUnaryOp Negation of instant
   * Goal 11. Weak Mutation 21: org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J:65 - ReplaceVariable value -> instant
   * Goal 12. Weak Mutation 22: org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J:65 - InsertUnaryOp Negation of value
   */

  

  //Test case number: 6
  /*
   * 13 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I: Line 148
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 77: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceConstant - 1 -> 0
   * Goal 10. Weak Mutation 78: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> %
   * Goal 11. Weak Mutation 79: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> -
   * Goal 12. Weak Mutation 80: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> *
   * Goal 13. Weak Mutation 81: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> /
   */

  

  //Test case number: 7
  /*
   * 36 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I: Line 148
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 85
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 86
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 87
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 88
   * Goal 8. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 90
   * Goal 9. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 10. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J
   * Goal 11. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 12. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J
   * Goal 13. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 14. Weak Mutation 44: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp Negation of value
   * Goal 15. Weak Mutation 45: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp IINC 1 value
   * Goal 16. Weak Mutation 46: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp IINC -1 value
   * Goal 17. Weak Mutation 47: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - ReplaceConstant - 1 -> 0
   * Goal 18. Weak Mutation 49: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp Negation of max
   * Goal 19. Weak Mutation 51: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp Negation of value
   * Goal 20. Weak Mutation 52: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp IINC 1 value
   * Goal 21. Weak Mutation 53: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp IINC -1 value
   * Goal 22. Weak Mutation 55: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp Negation of max
   * Goal 23. Weak Mutation 56: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp IINC 1 max
   * Goal 24. Weak Mutation 57: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp IINC -1 max
   * Goal 25. Weak Mutation 58: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - ReplaceComparisonOperator != -> -1
   * Goal 26. Weak Mutation 61: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:88 - ReplaceConstant - 0 -> 1
   * Goal 27. Weak Mutation 62: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - InsertUnaryOp Negation of instant
   * Goal 28. Weak Mutation 63: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - ReplaceVariable value -> max
   * Goal 29. Weak Mutation 64: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - InsertUnaryOp Negation of value
   * Goal 30. Weak Mutation 65: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - InsertUnaryOp IINC 1 value
   * Goal 31. Weak Mutation 66: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - InsertUnaryOp IINC -1 value
   * Goal 32. Weak Mutation 77: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceConstant - 1 -> 0
   * Goal 33. Weak Mutation 78: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> %
   * Goal 34. Weak Mutation 79: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> -
   * Goal 35. Weak Mutation 80: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> *
   * Goal 36. Weak Mutation 81: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> /
   */

  

  //Test case number: 8
  /*
   * 38 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I: Line 148
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 85
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 86
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 87
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 90
   * Goal 8. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 9. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J
   * Goal 10. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 11. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J
   * Goal 12. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 13. Weak Mutation 43: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - ReplaceVariable value -> max
   * Goal 14. Weak Mutation 44: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp Negation of value
   * Goal 15. Weak Mutation 45: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp IINC 1 value
   * Goal 16. Weak Mutation 46: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp IINC -1 value
   * Goal 17. Weak Mutation 47: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - ReplaceConstant - 1 -> 0
   * Goal 18. Weak Mutation 48: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - ReplaceVariable max -> value
   * Goal 19. Weak Mutation 49: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp Negation of max
   * Goal 20. Weak Mutation 50: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - ReplaceVariable value -> max
   * Goal 21. Weak Mutation 51: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp Negation of value
   * Goal 22. Weak Mutation 52: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp IINC 1 value
   * Goal 23. Weak Mutation 53: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp IINC -1 value
   * Goal 24. Weak Mutation 54: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - ReplaceVariable max -> value
   * Goal 25. Weak Mutation 55: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp Negation of max
   * Goal 26. Weak Mutation 56: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp IINC 1 max
   * Goal 27. Weak Mutation 57: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - InsertUnaryOp IINC -1 max
   * Goal 28. Weak Mutation 60: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:87 - ReplaceComparisonOperator != -> >
   * Goal 29. Weak Mutation 62: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - InsertUnaryOp Negation of instant
   * Goal 30. Weak Mutation 63: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - ReplaceVariable value -> max
   * Goal 31. Weak Mutation 64: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - InsertUnaryOp Negation of value
   * Goal 32. Weak Mutation 65: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - InsertUnaryOp IINC 1 value
   * Goal 33. Weak Mutation 66: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:90 - InsertUnaryOp IINC -1 value
   * Goal 34. Weak Mutation 77: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceConstant - 1 -> 0
   * Goal 35. Weak Mutation 78: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> %
   * Goal 36. Weak Mutation 79: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> -
   * Goal 37. Weak Mutation 80: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> *
   * Goal 38. Weak Mutation 81: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> /
   */

  

  //Test case number: 9
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfFloor(J)J: Line 190
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfFloor(J)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfFloor(J)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 100: org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfFloor(J)J:190 - InsertUnaryOp Negation of instant
   */

  

  //Test case number: 10
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfEven(J)J: Line 198
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfEven(J)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfEven(J)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 102: org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfEven(J)J:198 - InsertUnaryOp Negation of instant
   */

  

  //Test case number: 11
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfCeiling(J)J: Line 194
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfCeiling(J)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfCeiling(J)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 101: org.joda.time.field.ZeroIsMaxDateTimeField.roundHalfCeiling(J)J:194 - InsertUnaryOp Negation of instant
   */

  

  //Test case number: 12
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.roundFloor(J)J: Line 182
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.roundFloor(J)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.roundFloor(J)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 98: org.joda.time.field.ZeroIsMaxDateTimeField.roundFloor(J)J:182 - InsertUnaryOp Negation of instant
   */

  

  //Test case number: 13
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.roundCeiling(J)J: Line 186
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.roundCeiling(J)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.roundCeiling(J)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 99: org.joda.time.field.ZeroIsMaxDateTimeField.roundCeiling(J)J:186 - InsertUnaryOp Negation of instant
   */

  

  //Test case number: 14
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.remainder(J)J: Line 202
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.remainder(J)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.remainder(J)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 103: org.joda.time.field.ZeroIsMaxDateTimeField.remainder(J)J:202 - InsertUnaryOp Negation of instant
   */

  

  //Test case number: 15
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.isLeap(J)Z: Line 94
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.isLeap(J)Z
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.isLeap(J)Z
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 67: org.joda.time.field.ZeroIsMaxDateTimeField.isLeap(J)Z:94 - InsertUnaryOp Negation of instant
   */

  

  //Test case number: 16
  /*
   * 13 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;[I)I: Line 138
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;[I)I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;[I)I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 72: org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;[I)I:138 - ReplaceConstant - 1 -> 0
   * Goal 10. Weak Mutation 73: org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;[I)I:138 - ReplaceArithmeticOperator + -> %
   * Goal 11. Weak Mutation 74: org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;[I)I:138 - ReplaceArithmeticOperator + -> -
   * Goal 12. Weak Mutation 75: org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;[I)I:138 - ReplaceArithmeticOperator + -> *
   * Goal 13. Weak Mutation 76: org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;[I)I:138 - ReplaceArithmeticOperator + -> /
   */

  @Test public void test16()  throws Throwable  {
      ZeroIsMaxDateTimeField.clearORefMap();
	TestPreciseDateTimeField.MockStandardDateTimeField testPreciseDateTimeField_MockStandardDateTimeField0 = new TestPreciseDateTimeField.MockStandardDateTimeField();
      DateTimeFieldType dateTimeFieldType0 = DateTimeFieldType.secondOfMinute();
      ZeroIsMaxDateTimeField zeroIsMaxDateTimeField0 = new ZeroIsMaxDateTimeField((DateTimeField) testPreciseDateTimeField_MockStandardDateTimeField0, dateTimeFieldType0);
      LocalDateTime localDateTime0 = new LocalDateTime((-234L), (Chronology) null);
      int[] intArray0 = new int[3];
      int int0 = zeroIsMaxDateTimeField0.getMinimumValue((ReadablePartial) localDateTime0, intArray0);
	List obj_list_7au3e = (List) ZeroIsMaxDateTimeField.oref_map
			.get("getMinimumValue(ReadablePartial$int[])0");
	Object target_obj_7au3e = obj_list_7au3e.get(0);
	assertEquals(
			"(E)0,(C)org.joda.time.field.ZeroIsMaxDateTimeField,(MSIG)getMinimumValue(ReadablePartial$int[])0,(I)0",
			1l, ((Integer) target_obj_7au3e).longValue());
  }

  //Test case number: 17
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;)I: Line 129
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;)I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;)I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 71: org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(Lorg/joda/time/ReadablePartial;)I:129 - ReplaceConstant - 1 -> 0
   */

  

  //Test case number: 18
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(J)I: Line 120
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(J)I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(J)I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 70: org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue(J)I:120 - ReplaceConstant - 1 -> 0
   */

  

  //Test case number: 19
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue()I: Line 111
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue()I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue()I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 69: org.joda.time.field.ZeroIsMaxDateTimeField.getMinimumValue()I:111 - ReplaceConstant - 1 -> 0
   */

  

  //Test case number: 20
  /*
   * 13 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;[I)I: Line 178
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;[I)I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;[I)I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 93: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;[I)I:178 - ReplaceConstant - 1 -> 0
   * Goal 10. Weak Mutation 94: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;[I)I:178 - ReplaceArithmeticOperator + -> %
   * Goal 11. Weak Mutation 95: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;[I)I:178 - ReplaceArithmeticOperator + -> -
   * Goal 12. Weak Mutation 96: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;[I)I:178 - ReplaceArithmeticOperator + -> *
   * Goal 13. Weak Mutation 97: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;[I)I:178 - ReplaceArithmeticOperator + -> /
   */

  

  //Test case number: 21
  /*
   * 13 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;)I: Line 168
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;)I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;)I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 88: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;)I:168 - ReplaceConstant - 1 -> 0
   * Goal 10. Weak Mutation 89: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;)I:168 - ReplaceArithmeticOperator + -> %
   * Goal 11. Weak Mutation 90: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;)I:168 - ReplaceArithmeticOperator + -> -
   * Goal 12. Weak Mutation 91: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;)I:168 - ReplaceArithmeticOperator + -> *
   * Goal 13. Weak Mutation 92: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(Lorg/joda/time/ReadablePartial;)I:168 - ReplaceArithmeticOperator + -> /
   */

  

  //Test case number: 22
  /*
   * 14 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I: Line 158
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 82: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I:158 - InsertUnaryOp Negation of instant
   * Goal 10. Weak Mutation 83: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I:158 - ReplaceConstant - 1 -> 0
   * Goal 11. Weak Mutation 84: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I:158 - ReplaceArithmeticOperator + -> %
   * Goal 12. Weak Mutation 85: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I:158 - ReplaceArithmeticOperator + -> -
   * Goal 13. Weak Mutation 86: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I:158 - ReplaceArithmeticOperator + -> *
   * Goal 14. Weak Mutation 87: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue(J)I:158 - ReplaceArithmeticOperator + -> /
   */

  

  //Test case number: 23
  /*
   * 8 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getLeapDurationField()Lorg/joda/time/DurationField;: Line 102
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getLeapDurationField()Lorg/joda/time/DurationField;
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getLeapDurationField()Lorg/joda/time/DurationField;
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   */

  

  //Test case number: 24
  /*
   * 9 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getLeapAmount(J)I: Line 98
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getLeapAmount(J)I
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getLeapAmount(J)I
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 68: org.joda.time.field.ZeroIsMaxDateTimeField.getLeapAmount(J)I:98 - InsertUnaryOp Negation of instant
   */

  

  //Test case number: 25
  /*
   * 12 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.getDifferenceAsLong(JJ)J: Line 81
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.getDifferenceAsLong(JJ)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getDifferenceAsLong(JJ)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 39: org.joda.time.field.ZeroIsMaxDateTimeField.getDifferenceAsLong(JJ)J:81 - ReplaceVariable minuendInstant -> subtrahendInstant
   * Goal 10. Weak Mutation 40: org.joda.time.field.ZeroIsMaxDateTimeField.getDifferenceAsLong(JJ)J:81 - InsertUnaryOp Negation of minuendInstant
   * Goal 11. Weak Mutation 41: org.joda.time.field.ZeroIsMaxDateTimeField.getDifferenceAsLong(JJ)J:81 - ReplaceVariable subtrahendInstant -> minuendInstant
   * Goal 12. Weak Mutation 42: org.joda.time.field.ZeroIsMaxDateTimeField.getDifferenceAsLong(JJ)J:81 - InsertUnaryOp Negation of subtrahendInstant
   */

  

  //Test case number: 26
  /*
   * 25 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 53
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 54
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 55
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I: Line 57
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I: Line 148
   * Goal 8. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 9. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I
   * Goal 10. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 11. org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I
   * Goal 12. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 13. Weak Mutation 5: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:53 - InsertUnaryOp Negation of instant
   * Goal 14. Weak Mutation 6: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp Negation of value
   * Goal 15. Weak Mutation 7: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp IINC 1 value
   * Goal 16. Weak Mutation 8: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - InsertUnaryOp IINC -1 value
   * Goal 17. Weak Mutation 9: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:54 - ReplaceComparisonOperator != -> -1
   * Goal 18. Weak Mutation 12: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp Negation of value
   * Goal 19. Weak Mutation 13: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp IINC 1 value
   * Goal 20. Weak Mutation 14: org.joda.time.field.ZeroIsMaxDateTimeField.get(J)I:57 - InsertUnaryOp IINC -1 value
   * Goal 21. Weak Mutation 77: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceConstant - 1 -> 0
   * Goal 22. Weak Mutation 78: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> %
   * Goal 23. Weak Mutation 79: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> -
   * Goal 24. Weak Mutation 80: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> *
   * Goal 25. Weak Mutation 81: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> /
   */

  

  //Test case number: 27
  /*
   * 12 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(JI)J: Line 69
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(JI)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(JI)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 23: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(JI)J:69 - InsertUnaryOp Negation of instant
   * Goal 10. Weak Mutation 24: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(JI)J:69 - InsertUnaryOp Negation of value
   * Goal 11. Weak Mutation 25: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(JI)J:69 - InsertUnaryOp IINC 1 value
   * Goal 12. Weak Mutation 26: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(JI)J:69 - InsertUnaryOp IINC -1 value
   */

  

  //Test case number: 28
  /*
   * 12 covered goals:
   * Goal 1. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.add(JI)J: Line 61
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.add(JI)J
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.add(JI)J
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 15: org.joda.time.field.ZeroIsMaxDateTimeField.add(JI)J:61 - InsertUnaryOp Negation of instant
   * Goal 10. Weak Mutation 16: org.joda.time.field.ZeroIsMaxDateTimeField.add(JI)J:61 - InsertUnaryOp Negation of value
   * Goal 11. Weak Mutation 17: org.joda.time.field.ZeroIsMaxDateTimeField.add(JI)J:61 - InsertUnaryOp IINC 1 value
   * Goal 12. Weak Mutation 18: org.joda.time.field.ZeroIsMaxDateTimeField.add(JI)J:61 - InsertUnaryOp IINC -1 value
   */

  

  //Test case number: 29
  /*
   * 22 covered goals:
   * Goal 1. set(JI)J_org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException_EXPLICIT
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I: Line 148
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 85
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J: Line 86
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 8. org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J
   * Goal 9. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 10. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 11. Weak Mutation 43: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - ReplaceVariable value -> max
   * Goal 12. Weak Mutation 44: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp Negation of value
   * Goal 13. Weak Mutation 45: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp IINC 1 value
   * Goal 14. Weak Mutation 46: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp IINC -1 value
   * Goal 15. Weak Mutation 47: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - ReplaceConstant - 1 -> 0
   * Goal 16. Weak Mutation 48: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - ReplaceVariable max -> value
   * Goal 17. Weak Mutation 49: org.joda.time.field.ZeroIsMaxDateTimeField.set(JI)J:86 - InsertUnaryOp Negation of max
   * Goal 18. Weak Mutation 77: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceConstant - 1 -> 0
   * Goal 19. Weak Mutation 78: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> %
   * Goal 20. Weak Mutation 79: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> -
   * Goal 21. Weak Mutation 80: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> *
   * Goal 22. Weak Mutation 81: org.joda.time.field.ZeroIsMaxDateTimeField.getMaximumValue()I:148 - ReplaceArithmeticOperator + -> /
   */

  

  //Test case number: 30
  /*
   * 12 covered goals:
   * Goal 1. getDifference(JJ)I_java.lang.ArithmeticException_EXPLICIT
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I: Line 77
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 35: org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I:77 - ReplaceVariable minuendInstant -> subtrahendInstant
   * Goal 10. Weak Mutation 36: org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I:77 - InsertUnaryOp Negation of minuendInstant
   * Goal 11. Weak Mutation 37: org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I:77 - ReplaceVariable subtrahendInstant -> minuendInstant
   * Goal 12. Weak Mutation 38: org.joda.time.field.ZeroIsMaxDateTimeField.getDifference(JJ)I:77 - InsertUnaryOp Negation of subtrahendInstant
   */

  

  //Test case number: 31
  /*
   * 14 covered goals:
   * Goal 1. addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I: Line 73
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 28: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp Negation of fieldIndex
   * Goal 10. Weak Mutation 29: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp IINC 1 fieldIndex
   * Goal 11. Weak Mutation 30: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp IINC -1 fieldIndex
   * Goal 12. Weak Mutation 32: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp Negation of valueToAdd
   * Goal 13. Weak Mutation 33: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp IINC 1 valueToAdd
   * Goal 14. Weak Mutation 34: org.joda.time.field.ZeroIsMaxDateTimeField.addWrapField(Lorg/joda/time/ReadablePartial;I[II)[I:73 - InsertUnaryOp IINC -1 valueToAdd
   */

  

  //Test case number: 32
  /*
   * 12 covered goals:
   * Goal 1. add(JJ)J_org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException_EXPLICIT
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 50
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J: Line 65
   * Goal 5. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 6. org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J
   * Goal 7. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 8. Weak Mutation 0: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> -2
   * Goal 9. Weak Mutation 19: org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J:65 - ReplaceVariable instant -> value
   * Goal 10. Weak Mutation 20: org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J:65 - InsertUnaryOp Negation of instant
   * Goal 11. Weak Mutation 21: org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J:65 - ReplaceVariable value -> instant
   * Goal 12. Weak Mutation 22: org.joda.time.field.ZeroIsMaxDateTimeField.add(JJ)J:65 - InsertUnaryOp Negation of value
   */

  

  //Test case number: 33
  /*
   * 7 covered goals:
   * Goal 1. <init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 2. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 47
   * Goal 3. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V: Line 48
   * Goal 4. org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V
   * Goal 5. Weak Mutation 2: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:47 - ReplaceComparisonOperator == -> <=
   * Goal 6. Weak Mutation 3: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:48 - ReplaceConstant - Wrapped field's minumum value must be zero -> 
   * Goal 7. Weak Mutation 4: org.joda.time.field.ZeroIsMaxDateTimeField.<init>(Lorg/joda/time/DateTimeField;Lorg/joda/time/DateTimeFieldType;)V:48 - ReplaceComparisonOperator == -> !=
   */
}
