/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 10 01:46:23 GMT 2017
 */

package org.jfree.chart.plot;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.BasicStroke;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.Rectangle;
import java.awt.geom.Arc2D;
import java.awt.geom.Area;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.entity.EntityCollection;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotRenderingInfo;
import org.jfree.chart.plot.PlotState;
import org.jfree.chart.util.TableOrder;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.CategoryToPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultKeyedValuesDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.data.statistics.DefaultStatisticalCategoryDataset;
import org.junit.runner.RunWith;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.lang.reflect.Field;
import org.apache.commons.lang3.reflect.FieldUtils;
import static org.junit.Assert.*;
import myprinter.FieldPrinter;

public class DiffTGenTest0 {

  //Test case number: 0
  /*
   * 33 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>()V: Line 142
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z: Line 191
   * Goal 7. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 208
   * Goal 8. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 209
   * Goal 9. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 210
   * Goal 10. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 11. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z
   * Goal 12. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 13. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 14. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z
   * Goal 15. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 16. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 17. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 18. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 19. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 20. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 21. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 22. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 24. Weak Mutation 18: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_INTERIOR
   * Goal 25. Weak Mutation 19: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_PIE_AREA
   * Goal 26. Weak Mutation 20: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - ReplaceVariable darkerSides -> DEBUG_DRAW_LINK_AREA
   * Goal 27. Weak Mutation 21: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - InsertUnaryOp Negation
   * Goal 28. Weak Mutation 22: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_INTERIOR
   * Goal 29. Weak Mutation 23: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_PIE_AREA
   * Goal 30. Weak Mutation 24: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_LINK_AREA
   * Goal 31. Weak Mutation 25: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp Negation of darker
   * Goal 32. Weak Mutation 26: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC 1 darker
   * Goal 33. Weak Mutation 27: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC -1 darker
   */

  

  //Test case number: 1
  /*
   * 21 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>()V: Line 142
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1015
   * Goal 7. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1016
   * Goal 8. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 9. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z
   * Goal 10. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 11. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z
   * Goal 12. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 13. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 14. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 15. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 16. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 17. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 19. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 20. Weak Mutation 153: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1015 - ReplaceComparisonOperator != -> ==
   * Goal 21. Weak Mutation 154: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1016 - ReplaceConstant - 1 -> 0
   */

  

  //Test case number: 2
  /*
   * 18 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.getPlotType()Ljava/lang/String;: Line 978
   * Goal 6. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 7. org.jfree.chart.plot.PiePlot3D.getPlotType()Ljava/lang/String;
   * Goal 8. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 9. org.jfree.chart.plot.PiePlot3D.getPlotType()Ljava/lang/String;
   * Goal 10. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 11. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 12. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 13. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 14. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 15. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 128: org.jfree.chart.plot.PiePlot3D.getPlotType()Ljava/lang/String;:978 - ReplaceConstant - Pie_3D_Plot -> 
   */

  

  //Test case number: 3
  /*
   * 22 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.getDepthFactor()D: Line 163
   * Goal 6. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 7. org.jfree.chart.plot.PiePlot3D.getDepthFactor()D
   * Goal 8. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 9. org.jfree.chart.plot.PiePlot3D.getDepthFactor()D
   * Goal 10. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 11. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 12. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 13. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 14. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 15. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 8: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - ReplaceVariable depthFactor -> DEFAULT_INTERIOR_GAP
   * Goal 19. Weak Mutation 9: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - ReplaceVariable depthFactor -> MAX_INTERIOR_GAP
   * Goal 20. Weak Mutation 10: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - ReplaceVariable depthFactor -> DEFAULT_START_ANGLE
   * Goal 21. Weak Mutation 11: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - ReplaceVariable depthFactor -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 22. Weak Mutation 12: org.jfree.chart.plot.PiePlot3D.getDepthFactor()D:163 - InsertUnaryOp Negation
   */

  

  //Test case number: 4
  /*
   * 57 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1015
   * Goal 6. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1016
   * Goal 7. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1018
   * Goal 8. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1019
   * Goal 9. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1021
   * Goal 10. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1022
   * Goal 11. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1025
   * Goal 12. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1026
   * Goal 13. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 208
   * Goal 14. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 209
   * Goal 15. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V: Line 210
   * Goal 16. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 17. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 18. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 19. org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V
   * Goal 20. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 21. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 22. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 23. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 24. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 25. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 26. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 27. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 28. Weak Mutation 22: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_INTERIOR
   * Goal 29. Weak Mutation 23: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_PIE_AREA
   * Goal 30. Weak Mutation 24: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - ReplaceVariable darker -> DEBUG_DRAW_LINK_AREA
   * Goal 31. Weak Mutation 25: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp Negation of darker
   * Goal 32. Weak Mutation 26: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC 1 darker
   * Goal 33. Weak Mutation 27: org.jfree.chart.plot.PiePlot3D.setDarkerSides(Z)V:208 - InsertUnaryOp IINC -1 darker
   * Goal 34. Weak Mutation 153: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1015 - ReplaceComparisonOperator != -> ==
   * Goal 35. Weak Mutation 154: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1016 - ReplaceConstant - 1 -> 0
   * Goal 36. Weak Mutation 155: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1018 - ReplaceComparisonOperator != -> ==
   * Goal 37. Weak Mutation 156: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1019 - ReplaceConstant - 0 -> 1
   * Goal 38. Weak Mutation 157: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_INTERIOR_GAP
   * Goal 39. Weak Mutation 158: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> MAX_INTERIOR_GAP
   * Goal 40. Weak Mutation 159: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_START_ANGLE
   * Goal 41. Weak Mutation 160: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 42. Weak Mutation 161: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - InsertUnaryOp Negation
   * Goal 43. Weak Mutation 162: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable that -> this
   * Goal 44. Weak Mutation 163: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_INTERIOR_GAP
   * Goal 45. Weak Mutation 164: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> MAX_INTERIOR_GAP
   * Goal 46. Weak Mutation 165: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_START_ANGLE
   * Goal 47. Weak Mutation 166: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 48. Weak Mutation 167: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - InsertUnaryOp Negation
   * Goal 49. Weak Mutation 168: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceComparisonOperator == -> -2
   * Goal 50. Weak Mutation 172: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - ReplaceVariable darkerSides -> DEBUG_DRAW_INTERIOR
   * Goal 51. Weak Mutation 173: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - ReplaceVariable darkerSides -> DEBUG_DRAW_PIE_AREA
   * Goal 52. Weak Mutation 174: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - ReplaceVariable darkerSides -> DEBUG_DRAW_LINK_AREA
   * Goal 53. Weak Mutation 175: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - InsertUnaryOp Negation
   * Goal 54. Weak Mutation 176: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - ReplaceVariable that -> this
   * Goal 55. Weak Mutation 180: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - InsertUnaryOp Negation
   * Goal 56. Weak Mutation 181: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - ReplaceComparisonOperator == -> !=
   * Goal 57. Weak Mutation 182: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1026 - ReplaceConstant - 0 -> 1
   */

  

  //Test case number: 5
  /*
   * 40 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1015
   * Goal 6. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1018
   * Goal 7. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1019
   * Goal 8. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1021
   * Goal 9. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1022
   * Goal 10. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1025
   * Goal 11. org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z: Line 1028
   * Goal 12. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 13. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 14. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 15. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 16. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 17. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 18. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 19. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 20. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 22. Weak Mutation 153: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1015 - ReplaceComparisonOperator != -> ==
   * Goal 23. Weak Mutation 155: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1018 - ReplaceComparisonOperator != -> ==
   * Goal 24. Weak Mutation 156: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1019 - ReplaceConstant - 0 -> 1
   * Goal 25. Weak Mutation 157: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_INTERIOR_GAP
   * Goal 26. Weak Mutation 158: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> MAX_INTERIOR_GAP
   * Goal 27. Weak Mutation 159: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_START_ANGLE
   * Goal 28. Weak Mutation 160: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 29. Weak Mutation 161: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - InsertUnaryOp Negation
   * Goal 30. Weak Mutation 162: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable that -> this
   * Goal 31. Weak Mutation 163: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_INTERIOR_GAP
   * Goal 32. Weak Mutation 164: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> MAX_INTERIOR_GAP
   * Goal 33. Weak Mutation 165: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_START_ANGLE
   * Goal 34. Weak Mutation 166: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceVariable depthFactor -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 35. Weak Mutation 167: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - InsertUnaryOp Negation
   * Goal 36. Weak Mutation 168: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1022 - ReplaceComparisonOperator == -> -2
   * Goal 37. Weak Mutation 175: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 176: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - ReplaceVariable that -> this
   * Goal 39. Weak Mutation 180: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - InsertUnaryOp Negation
   * Goal 40. Weak Mutation 181: org.jfree.chart.plot.PiePlot3D.equals(Ljava/lang/Object;)Z:1025 - ReplaceComparisonOperator == -> !=
   */

  

  //Test case number: 6
  /*
   * 17 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 5. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V: Line 231
   * Goal 6. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 7. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V
   * Goal 8. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 9. org.jfree.chart.plot.PiePlot3D.draw(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Point2D;Lorg/jfree/chart/plot/PlotState;Lorg/jfree/chart/plot/PlotRenderingInfo;)V
   * Goal 10. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 11. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 12. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 13. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 14. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 15. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   */

  @Test public void test6()  throws Throwable  {
	Object target_obj_7au3e = null;
	boolean not_thrown = false;
	try {
		PiePlot3D.clearORefMap();
		DefaultStatisticalCategoryDataset defaultStatisticalCategoryDataset0 = new DefaultStatisticalCategoryDataset();
		TableOrder tableOrder0 = TableOrder.BY_COLUMN;
		CategoryToPieDataset categoryToPieDataset0 = new CategoryToPieDataset(
				(CategoryDataset) defaultStatisticalCategoryDataset0,
				tableOrder0, (-48));
		PiePlot3D piePlot3D0 = new PiePlot3D((PieDataset) categoryToPieDataset0);
		JTable jTable0 = new JTable();
		JTableHeader jTableHeader0 = jTable0.getTableHeader();
		Rectangle rectangle0 = jTableHeader0.getHeaderRect((-48));
		PlotState plotState0 = new PlotState();
		ChartRenderingInfo chartRenderingInfo0 = new ChartRenderingInfo(
				(EntityCollection) null);
		PlotRenderingInfo plotRenderingInfo0 = chartRenderingInfo0
				.getPlotInfo();
		piePlot3D0.draw((Graphics2D) null, rectangle0, (Point2D) null,
				plotState0, plotRenderingInfo0);
		not_thrown = true;
		fail();
	} catch (Throwable t) {
		if (not_thrown) {
			fail("Throwable Expected!");
		} else {
			List obj_list_7au3e = (List) PiePlot3D.oref_map
					.get("draw(Graphics2D$Rectangle2D$Point2D$PlotState$PlotRenderingInfo)0");
			target_obj_7au3e = obj_list_7au3e.get(0);
			assertEquals(
					"(E)0,(C)org.jfree.chart.plot.PiePlot3D,(MSIG)draw(Graphics2D$Rectangle2D$Point2D$PlotState$PlotRenderingInfo)0,(I)0",
					"java.lang.NullPointerException",
					((Throwable) target_obj_7au3e).toString());
		}
	}
}

  //Test case number: 7
  /*
   * 25 covered goals:
   * Goal 1. org.jfree.chart.plot.PiePlot3D.<init>()V: Line 142
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V: Line 175
   * Goal 7. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V: Line 176
   * Goal 8. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V: Line 177
   * Goal 9. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 10. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V
   * Goal 11. org.jfree.chart.plot.PiePlot3D.<init>()V
   * Goal 12. org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V
   * Goal 13. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 14. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 15. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 16. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 17. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 18. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 19. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 20. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 13: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - ReplaceVariable factor -> DEFAULT_INTERIOR_GAP
   * Goal 22. Weak Mutation 14: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - ReplaceVariable factor -> MAX_INTERIOR_GAP
   * Goal 23. Weak Mutation 15: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - ReplaceVariable factor -> DEFAULT_START_ANGLE
   * Goal 24. Weak Mutation 16: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - ReplaceVariable factor -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 25. Weak Mutation 17: org.jfree.chart.plot.PiePlot3D.setDepthFactor(D)V:175 - InsertUnaryOp Negation of factor
   */

  

  //Test case number: 8
  /*
   * 42 covered goals:
   * Goal 1. drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 126
   * Goal 3. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 134
   * Goal 4. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 152
   * Goal 5. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V: Line 153
   * Goal 6. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 621
   * Goal 7. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 629
   * Goal 8. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 630
   * Goal 9. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 631
   * Goal 10. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V: Line 633
   * Goal 11. org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z: Line 191
   * Goal 12. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 13. org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V
   * Goal 14. org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V
   * Goal 15. Weak Mutation 0: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 0.0
   * Goal 16. Weak Mutation 1: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.0
   * Goal 17. Weak Mutation 2: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -1.0
   * Goal 18. Weak Mutation 3: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> -0.88
   * Goal 19. Weak Mutation 4: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:126 - ReplaceConstant - 0.12 -> 1.12
   * Goal 20. Weak Mutation 5: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:134 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 6: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 22. Weak Mutation 7: org.jfree.chart.plot.PiePlot3D.<init>(Lorg/jfree/data/general/PieDataset;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 21: org.jfree.chart.plot.PiePlot3D.getDarkerSides()Z:191 - InsertUnaryOp Negation
   * Goal 24. Weak Mutation 28: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:621 - ReplaceComparisonOperator == -> !=
   * Goal 25. Weak Mutation 44: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> extent
   * Goal 26. Weak Mutation 45: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_INTERIOR_GAP
   * Goal 27. Weak Mutation 46: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> MAX_INTERIOR_GAP
   * Goal 28. Weak Mutation 47: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_START_ANGLE
   * Goal 29. Weak Mutation 48: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable start -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 30. Weak Mutation 49: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of start
   * Goal 31. Weak Mutation 50: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> start
   * Goal 32. Weak Mutation 51: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_INTERIOR_GAP
   * Goal 33. Weak Mutation 52: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> MAX_INTERIOR_GAP
   * Goal 34. Weak Mutation 53: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_START_ANGLE
   * Goal 35. Weak Mutation 54: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceVariable extent -> DEFAULT_MINIMUM_ARC_ANGLE_TO_DRAW
   * Goal 36. Weak Mutation 55: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - InsertUnaryOp Negation of extent
   * Goal 37. Weak Mutation 56: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> %
   * Goal 38. Weak Mutation 57: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> -
   * Goal 39. Weak Mutation 58: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> *
   * Goal 40. Weak Mutation 59: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:631 - ReplaceArithmeticOperator + -> /
   * Goal 41. Weak Mutation 60: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_LABEL_OUTLINE_STROKE
   * Goal 42. Weak Mutation 61: org.jfree.chart.plot.PiePlot3D.drawSide(Ljava/awt/Graphics2D;Ljava/awt/geom/Rectangle2D;Ljava/awt/geom/Arc2D;Ljava/awt/geom/Area;Ljava/awt/geom/Area;Ljava/awt/Paint;Ljava/awt/Paint;Ljava/awt/Stroke;ZZ)V:633 - ReplaceVariable outlineStroke -> DEFAULT_OUTLINE_STROKE
   */
}
